### ISSUE TITLE
If you disable or bypass a node with no connection, it stops the whole workflow from running

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [chrisgoringe/cg-use-everywhere#10]
Using the ComfyUI inbuilt feature to disable/bypass a node should allow the workflow to run without that node, but when it is connected via a UE node, it breaks the workflow. I have a workflow that saves an image before upscaling and then saves after upscaling. If I bypass(ctrl+b) or disable(ctrl+m) the save node, it should just prevent it from saving but run the rest of the flow, but it just doesn't run anything.

**Comment by chrisgoringe** [comment]
Could you upload a workflow that illustrates the problem?

**Comment by chrisgoringe** [comment]
Correct behaviour would be that if a UE node is disabled or bypassed, it doesn't broadcast, but nothing else changes.

The issue may be that the way the nodes work is to tell the receiver that it is connected to the node upstream of the UE node. So the UE node being bypassed might not stop the broadcast.

Will explore further.

**Comment by chrisgoringe** [comment]
If either the upstream or downstream nodes that are connected by a UE are set to bypass, it generates a js error 

use_everywhere.js:159 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'inputs')
    at use_everywhere.js:159:51

**Comment by chrisgoringe** [comment]
I think this is now working correctly in the latest commit. If not, please give example and reopen (or create new issue).
