### ISSUE TITLE
Anything for filename_prefix

### ISSUE THREAD

**Issue by PabloMontero** [chrisgoringe/cg-use-everywhere#100]
Using Anything to connect with filename_prefix of Save Image node.

I know it requires a Primitive and as far as I know it's tricky at this moment to handle.

Is there a workaround? I have a matrix of, let's say, 3x4 images and I want to name them like:

AA, AB, AC, AD
BA, BB, BC, BD
CA, CB, CC, CD

The current naming method is a real pain IMO. Any recommendation?

Thank you!

**Comment by PabloMontero** [comment]
Just seen WAS nodes has tokens, very useful for this task.

https://www.reddit.com/r/comfyui/comments/16d03q7/using_seed_as_an_output_folder_name/

**Comment by chrisgoringe** [comment]
I connect to the filename_prefix input all the time, with no problems. It doesn't need to be a primitive, that input takes a string.
