### ISSUE TITLE
Easier editing of `everywhere` links

### ISSUE THREAD

**Issue by mijuku233** [chrisgoringe/cg-use-everywhere#101]
I have an idea that will make it easier for `everywhere` to set which links are connected and which are not.

Added `output` to `everywhere`, when dragging the `output` link to `input`, the UE link is established immediately.
And add a `Disconnect UE link` option to the right-click menu on `Input`.

**Comment by chrisgoringe** [comment]
It's not clear to me how this would interact with the existing connection method...

**Comment by mijuku233** [comment]
> It's not clear to me how this would interact with the existing connection method...

I made a gif to show how it interacts

![UE](https://github.com/chrisgoringe/cg-use-everywhere/assets/89350747/46636f17-dae4-4654-92fe-bb8cd49ab312)

**Comment by chrisgoringe** [comment]
But that link would already have been there according to the way UE currently works

**Comment by mijuku233** [comment]
> But that link would already have been there according to the way UE currently works

Suppose I use everywhere? and make it not linked to any input, then I can quickly set which to be linked in this way

**Comment by chrisgoringe** [comment]
Seems to me to go against the whole point of UE nodes, which is that you *don't* have to make connections... if you are going to make and break them manually, why not just use normal links?

**Comment by mijuku233** [comment]
> Seems to me to go against the whole point of UE nodes, which is that you _don't_ have to make connections... if you are going to make and break them manually, why not just use normal links?

Maybe `Disconnect UE link` on the `Input` menu is more useful when you don't want an input to be linked.

**Comment by chrisgoringe** [comment]
What's the use case for this? 

If you don't want UE to connect to a required input, you must want something else to connect to it. So just connect that thing.

Disconnect UE would only make sense for an optional input, which is an unusual enough situation that I doubt it justifies the increased complexity of UI and code.

**Comment by mijuku233** [comment]
> What's the use case for this?
> 
> If you don't want UE to connect to a required input, you must want something else to connect to it. So just connect that thing.
> 
> Disconnect UE would only make sense for an optional input, which is an unusual enough situation that I doubt it justifies the increased complexity of UI and code.

The reason why I proposed this idea is that another idea of mine may require this function, but you are right, in general, this function is not necessary

**Comment by mijuku233** [comment]
@chrisgoringe I wanted to convert `everywhere` to a group node with some nodes that are commonly used, but `everywhere` fails when converted to a group node, and I don't know if this problem can be solved, so I talked to another custom node author [ComfyUI-Easy-Use](https://github.com/yolain/ComfyUI-Easy-Use) and asked him to add `everywhere` to the `easyloader`, but he thought it was a bit complicated and suggested that I mention this idea to you

**Comment by mijuku233** [comment]
This is an unwanted idea, so I'm going to close this issue and submit the bug about the `group node` to a new issue.
