### ISSUE TITLE
Issue with adding templates with nodes that use forceInput when UE enabled

### ISSUE THREAD

**Issue by aegis72** [chrisgoringe/cg-use-everywhere#103]
https://www.youtube.com/watch?v=wBQt9jyq8ZU

When I place templates, the UE links (while valid) don't get "made" all the time, requiring a refresh of the window (f5). Then (assuming the issue wasn't because of a clash) the UE links redraw great and everything works.

If fixing that isn't possible because "templates," it would be nice to have a "force UE Link Refresh" in right-click, or a button somewhere in manager or upper-right or something rather than the page refresh, which "feels" broken. Video above shows behavior. wiggling stuff or updating a title or whatever doesn't force the redraw either; only f5 works.

This is limited to template additions; workflows are instantiated as one big thing I suppose, and so don't have this issue.

**Comment by aegis72** [comment]
No refresh, freshly placed: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/2e8086a4-aa91-4fde-ad52-34a06d136eca)

After page refresh:
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/ab2ee3f3-238e-4ec8-9b31-ec515e394445)

**Comment by chrisgoringe** [comment]
Just check this: after placing a template, instead of reloading the page, just move one of the new nodes around a bit. 

Also, could you check the JavaScript console (f12) for messages that might suggest a problem?

"Force ue link refresh" doesn't actually make sense because of the way ue links work (they are always calculated on the fly)

**Comment by aegis72** [comment]
Sure, happy to look at console. But yeah, I know that a jiggle or update usually will fix it. In this case, that doesn't happen, but they wire up fine after a refresh (and as you see in the video, no conflicts are reporting prior to refresh).

**Comment by aegis72** [comment]
Just noticed too that I am behind (updating nodes now) so I can ensure that I am working from latest.

**Comment by chrisgoringe** [comment]
Could you clarify; are the UE nodes that aren't working part of the template being added? Or are they already part of the workflow but not connecting to the newly added nodes?

**Comment by aegis72** [comment]
https://youtu.be/hiCvOB3oPGc

"Maximum Call Stack Size Exceeded."

And yes, they are part of the templates.

**Comment by aegis72** [comment]
The workflow doesn't exist before the templates are added; the templates are used to build workflows out of modules, and the modules get tied together by UE so no wiring needs to be done.

**Comment by aegis72** [comment]
they work, in the context of "once I hit f5, they work as expected." It is STILL way better than wiring tons of stuff up :).

**Comment by chrisgoringe** [comment]
Ok, so ue nodes are part of the template. I'll need to look into the code (away from desk right now) but I suspect the issue is that some initialisation of the UE nodes doesn't happen when they are added as part of a template (I don't use templates...).

If I'm right it should be fairly easy to fix.

**Comment by chrisgoringe** [comment]
Oh, just saw that you posted a video. Maximum call stack... that means a recursion error. That's where I'll start looking!

**Comment by aegis72** [comment]
UE nodes are part of ALL of the templates :). Let me attach a WF with those same three modules already placed. Then, you can resolve any dependencies in them, select the contents of each group as templates 1, 2, 3 or whatever, and see what I see, if needed. I recommend this way, because unlike workflows, templates don't check for missing nodes first, they just load and any nodes not present are simply deleted/not present, leading to problems.

For my users, this isn't a worry as we resolve all dependencies before any templates are used, but for others it can cause problems.

[XL_for-chris.zip](https://github.com/chrisgoringe/cg-use-everywhere/files/14060639/XL_for-chris.zip)

**Comment by chrisgoringe** [comment]
I can't initially reproduce this: simple templates containing UE nodes can be added to a workflow without problem.

So I suspect there is a compatibility issue with one of the other custom nodes (of which you seem to have a lot!)

Unfortunately the resolution on the video wasn't great - at one point you read out a line from the error message that related to UE (use everywhere ui line 132 I think). It would be helpful to get a screenshot of that part of the error - something like this but in better resolution!

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/680c3c15-cc74-4bec-ab82-66a693557285)

I'll set up a clean Comfy Install and try to get all the custom nodes you use to test with :)

**Comment by aegis72** [comment]
Do you think it could be the NUMBER of them? Ill get better res now that you get the idea of what's happening---but I use a LOT of UE nodes. There's 38 in those 3 modules alone :)

**Comment by aegis72** [comment]
Also, if you'd like I can get you the current state of "everything" so that you could have the whole system, for future testing if anything comes up. I suspect that I am using your nodes in my WFs more than almost anyone, so my WFs make a fairly good stress test :).

**Comment by chrisgoringe** [comment]
Try disabling the WAS Node Suite. 

The infinite recursion is happening inside Text Concatenate from that pack (I think).

It may still be UE related, but if you can check for me...

**Comment by aegis72** [comment]
I will try; I have just mmade a new install to test clean w/ only nodes my WF uses

**Comment by aegis72** [comment]
So, barebones install (only the nodes I require, fresh install) 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/f87ba610-8dc5-4a5c-b938-f69dc0e5e20f)

hopefully this is better res

**Comment by aegis72** [comment]
Console after refresh sent. Some nodes will be missing from WAS here but can't be helped. UE does work after refresh as before. I can keep disabling stuff; will try the smaller suites and move downwards
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/84450441-2bda-4f06-b1b6-4d7078430ad3)

**Comment by aegis72** [comment]
If I ONLY place the Commons, the one internal link does show: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/78e3e980-0526-48f4-b472-e926af059a31)
 
If I go 0a , then 1a (loader) I get the errors: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/69a35d9a-f93e-4a0d-9661-154f178f1cc0)

If a template is placed that has no send outputs (in this case 10 saver: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/8988f208-8a31-47c8-993a-ec4d69b83dfd)
 UE links persist.

Adding in a second sampler will disable them again, until refresh: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/398c0fbe-1c2d-41dc-b723-f5b2098e73d0)

**Comment by chrisgoringe** [comment]
Thanks for all that! Lots of data.... I probably won't be able to do any more testing until after the weekend though :)

**Comment by aegis72** [comment]
Testing this morning; 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/93f2c06d-e573-4114-9d13-91dfbfd9062c)

Here, I created a series of Simple strings connected to a concat node and passed to a 

after refresh
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/40c2b8f6-99a6-461c-b57e-5a71640bcd30)

Video that shows the issue and what I think is happening:
https://www.youtube.com/watch?v=zxzpa56uILM

Zip of these 3 simple test templates (import using right click>node templates>manage>import
[test_templates.zip](https://github.com/chrisgoringe/cg-use-everywhere/files/14072966/test_templates.zip)

**Comment by aegis72** [comment]
That said, I think the problem above is disconnected from mine. In my case, the issue is this node: 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/58f8314a-51df-49cb-b1cf-cb5074ca16df)

But that isn't the case in the problem above. So I think I might be finding two issues; one is with my MultiPipe node (weird that it doesn't have any issues on its own though), and the other being this group Regex non-update.

**Comment by aegis72** [comment]
On my side, if I disconnect all the node inputs from that multipipe (they are not fed on the loader by UE, btw, but are wired) then eventually, UE nodes come back and the error stops. Here's the weird bit:
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/a6fcaf6d-8eb6-46ae-9da1-46993444217f)
If I then connect the wires back (I did from the bottom up, using some dummy values for image input and image dimension) then the wires stay on. 

So, I saved THAT config out as a template, and I built it using that. The error returned...but all I had to do to get the lines back was mute and unmute the pipe.

**Comment by aegis72** [comment]
FIRST, I can confirm that my problem is MY problem; IE it is my MultiPipe Node that is somehow weird, not UE in this case. I made this test template:
[fake multipipe.json](https://github.com/chrisgoringe/cg-use-everywhere/files/14073649/fake.multipipe.json)
and it has this issue too, no UE nodes present. I can load as a template, I get the error when any of the "ints" in the node (last 4 inputs) are connected. Muting the node stops it, unmuting starts it. Refresh stops it permanently (for reasons unknown at this time.

I'm looking at that on my end.

Second though the test rig a few posts up still show a weird behavior with the Group Regex and how it doesn't re-connect things when a simple string is connected as the regex and changed. That still seems like a UE thing.

**Comment by aegis72** [comment]
Actually, now that I think of it: 

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/6d862a71-31b6-4c12-8acc-3e888aa583f0)

There are no UE nodes in use here.

**Comment by aegis72** [comment]
Finally, one last data point; you can right click / fix node/ recreate and it also stops the error 

https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/1440b651-f017-442e-8f27-fbb6265bc2fc

**Comment by chrisgoringe** [comment]
Lots of data there...

From your last couple, it looks like the problem might be the way UE is interacting with the way forceInput is implemented; that makes sense in terms of where the error is (in widget code). 

The way lots of custom stuff gets done in comfy (in JavaScript in general, in fact) is to hijack a call: basically you take a reference to a function on an object, and replace that function with a new one which in turn calls the old one.

This class of bug occurs when that hijack is done twice, so the "old function" you are calling is in fact your new function, so when it calls the "old function" it's calling itself: hence infinite regression.

So something about adding some nodes (maybe just ones with forceInput?) in a template looks to be causing some widget code to be replaced twice. But if the node is recreated and reloaded the way it gets added doesn't have this bug.

Hopefully I now have enough information for when I get back to my desk!

**Comment by aegis72** [comment]
yeah, the error  happenson any node that uses that; i tried it with a single MTB int to number node. disabling ue clears the error.

**Comment by chrisgoringe** [comment]
Great. I should be able to find and fix!

**Comment by aegis72** [comment]
Thanks a ton. Kofi on the way come payday :).  Should the second group regex issue be spun off on its own? i don't believe it is connected to this issue.

**Comment by chrisgoringe** [comment]
Yes, raise a separate issue for that

**Comment by aegis72** [comment]
Done.; Issue 104

**Comment by chrisgoringe** [comment]
So I'm still struggling to reproduce this: I created a template using nodes with forceInput (from the WAS suite) and I can paste the template without generating an error.

Which makes me think there is an interaction between custom nodes going on here.

Could you post a list of all the custom nodes you have? A directory listing of your custom_nodes folder would do the job. I'd like to try to reproduce your setup!

**Comment by aegis72** [comment]
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/0035b9c5-ad83-472b-8d6b-b3b08bff75ca)
sorry is coming as a screenshot, im remoting to pc becauseof covid

**Comment by aegis72** [comment]
hey there. noticed that was forcedinputs are all text, whereas i was using an int forcedinput. on a hunch, i wanted to run a new test, and i was able to reproduce. heres what i did in order:
1) fresh comfyui
2) install manager
3) install UE
4) install was
5) updated cui
6) in looking for a forceinput int, noticed was didnt have one.
7) installed mtb
8) made template with an int forced input.
9) turned on showue, all good.
10 deleted the nods used to make the template
11) placed the two nodes as a template; links deactivated immediately
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/4c19e2ee-a326-4387-b4ce-6c364334d5ef)

**Comment by aegis72** [comment]
Triple Coffees sent to you sir :)!

**Comment by aegis72** [comment]
Hope all is OK!

**Comment by chrisgoringe** [comment]
Analysis - hideWidget is being called twice; it hijacks serializeValue; doing this twice for the same node causes an infinite loop.

When an `Int to Number (mtb)` node is added, the `hideWidget` method gets called (as expected):
![Screenshot 2024-02-12 081655](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/c3bf8ad8-06df-4bf0-a277-79a77cbea7de)

If you save the node as a template, the method is called twice (bad...)
![Screenshot 2024-02-12 081855](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/c6da038f-3038-4f45-bd21-4064e2761c4e)
![Screenshot 2024-02-12 081906](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/aa41cd3e-b574-4b04-95ea-36299943c15d)

When you load that template, the method is called twice (even if the template is just that node)
![Screenshot 2024-02-12 082235](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/211b7347-9b70-409b-af5a-ac9c00ff994a)
![Screenshot 2024-02-12 082242](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/b8c62c68-2f0a-4405-a3d5-aa8a2452139e)

**Comment by chrisgoringe** [comment]
So this is definitely a bug in the underlying code.

Delete all custom nodes, and add a single, trivial one:

```python
class IntToInt:
    @classmethod
    def INPUT_TYPES(cls):
        return {"required": { "int": ( "INT", { "default": 0, "forceInput": True, }, ), } }

    RETURN_TYPES = ("INT",)
    FUNCTION = "int_to_int"
    CATEGORY = "test"

    def int_to_int(self, int):
        return (int,)
    
NODE_CLASS_MAPPINGS = { "int to int" : IntToInt }
```

Add this node and a primitive:
![Screenshot 2024-02-12 083946](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/cde071b8-1232-40d4-8587-dc43928f3bb5)

Make these two nodes a template, delete them, add them back as a template, then click QueuePrompt and you get the same infinite loop:

![Screenshot 2024-02-12 084033](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/87d459bb-6fa5-4282-a2bd-abd9b626b3da)

**Comment by chrisgoringe** [comment]
Added issue https://github.com/comfyanonymous/ComfyUI/issues/2766 and PR https://github.com/comfyanonymous/ComfyUI/pull/2767 at Comfy.

In the meantime, the fix is to edit `web/extensions/core/widgetInputs.js` by inserting one new line (at line 25)

```javascript
function hideWidget(node, widget, suffix = "") {
	if (widget.type?.startsWith(CONVERTED_TYPE)) return;
	widget.origType = widget.type;
```

**Comment by aegis72** [comment]
rad, thx. i was getting a bit worried about you, if you were OK! Glad my concern was unfounded.

**Comment by chrisgoringe** [comment]
Thanks! I'm fine, just busy with my real job!

**Comment by aegis72** [comment]
same here. glad all is well
