### ISSUE TITLE
[Issue] UE Links with Group RegEx using simple string input not updating when Group Target Regex string is updated

### ISSUE THREAD

**Issue by aegis72** [chrisgoringe/cg-use-everywhere#104]
Steps to reproduce:
Using the test templates provided:
1) load the 3 test test templates as templates through the template manager (right click>node templates>manage>import
2) place template "test_ue_links_string_direct"
3) place template "GroupX". If not using AegisFlow Utility Nodes, place in a group called "GroupX"
4)  Place a second "GroupX", and place in a group called "GroupY" If you are using AF utility nodes, then change the auto-named group to "GroupY" from "GroupX"
5) Place a second "test_ue_links_string_direct". This will produce clashes with GroupX's inputs.
6) Change the purple top node string to "GroupY". Clashes should be resolved, but are not. Wiggle some nodes; fix is not applied.
7) Refresh page in browser. All clashes are removed.
*Note: Test was performed w/ AegisFlow Util nodes disabled to ensure our auto-grouping and naming wasn't part of the problem)

Images and Video below:

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/93f2c06d-e573-4114-9d13-91dfbfd9062c)

after refresh
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/40c2b8f6-99a6-461c-b57e-5a71640bcd30)

Video that shows the issue and what I think is happening:
https://www.youtube.com/watch?v=zxzpa56uILM

Zip of these 3 simple test templates (import using right click>node templates>manage>import
[test_templates.zip](https://github.com/chrisgoringe/cg-use-everywhere/files/14072966/test_templates.zip)

Confirming that the issue only happens when using Group Regex as an input; in widget mode the refresh is not required to clear the clash condition:
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/98e9779a-26f7-4a49-ac07-6e2607eba883)
.

**Comment by chrisgoringe** [comment]
Confirmed that I can reproduce this error. Looking into it.

**Comment by chrisgoringe** [comment]
OK, pushed a fix for this one. Note that the fix only works if the upstream node is the provided Simple String.

**Comment by chrisgoringe** [comment]
resolved in 4.7.13
