### ISSUE TITLE
After adding, click on the add task queue and do not run the added task. The plugin must be uninstalled to continue executing the task

### ISSUE THREAD

**Issue by lyg1980113** [chrisgoringe/cg-use-everywhere#106]
After adding, click on the add task queue and do not run the added task. The plugin must be uninstalled to continue executing the task

**Comment by chrisgoringe** [comment]
Please could you install, and then look at the JavaScript console (press f12) and look for any errors?

**Comment by aegis72** [comment]
Also check if a page refresh allows you to generate, as this happens to due to the previous issues 103 and 104.
