### ISSUE TITLE
Issues with everything, 

### ISSUE THREAD

**Issue by BliNDF123** [chrisgoringe/cg-use-everywhere#107]
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/16617464/60294996-b59d-4e9b-afc2-e5eff123835d)
Everything seemed to be working fine till I dropped in the Seed node part just to see it, didn't use it, and then started noticing some issues.  Seed on my KSamplers kept locking to a seed and I had to keep resetting it back to random almost every time I wanted to Queue something up, I cleared my whole workflow to see if that would fix it but now I'm having this problem above.  I use a Anything Everywhere3 for Model, Cond+, Cond-, but now as soon as I give it the first Conditioning+ it shows both the + and - as connected, and when I connect the second one, Conditioning-, all turn off.  Console is just spamming what you see in the screenshot.
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/16617464/41aac26e-53c5-4f15-b6cc-cfe2d8b312ef)
You can see VAE is connected fine by itself, and Model actually too from the Anything Everywhere3, but all conditioning turned off as soon as I hooked both up.
I actually just tried to use the single Anything Everywhere for the Conditioning but I already had them both glowing when I connected the first one. 
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/16617464/5f54a8b3-ad99-4bba-bfa0-c432b0d70bdc)

EDIT:  Actually, I was noticing I could click on ANY node when I had KSampler set to Random and the seed would lock to something, set it to Random again and click ANYWHERE on a node, even just up in an empty space in the KSampler and it would lock onto a seed, and not just on a single KSampler, all of them.  I uninstalled UE Nodes and it went back to normal.

**Comment by chrisgoringe** [comment]
Connecting two conditioning to a a ue3 node makes no sense - it has no way to know that one is meant to be + and the other -. 

Ue3 is designed for checkpoint (model, clip, vae). 

Use prompt anywhere for a pair of conditioning
