### ISSUE TITLE
[ beautifying ] add color to the wires

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-use-everywhere#110]
If the wires had color, the UI would look better, and it would also be easier to identify the node connections.

For instance, here I have a "switch", between img2img and text2img.

![UE](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/9902895f-91b5-4472-af58-657133355d6d)

**Comment by chrisgoringe** [comment]
Do you mean the colour of the UE wires when they are being displayed? Or the colour of the wires connected to the UE nodes (like the one between Upscale Image and Anything Everywhere in the image you posted)?

**Comment by JorgeR81** [comment]
I'm not talking about the "invisible" wires after the UE nodes.

I meant the ( pale green ) wires between the native Comfy UI nodes and the UE nodes. 
I think they should get the color of the previous connection, instead of being pale green.
