### ISSUE TITLE
Cannot queue anymore (compatibility with rgthree?)

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [chrisgoringe/cg-use-everywhere#116]
After installing this extension and setting up my everywhere nodes, clicking "Queue Prompt" does nothing. I have to disable the extension in order to do anything.

**Comment by chrisgoringe** [comment]
can you look in your javascript console (f12) to see if there are any errors being reported? This is almost certainly a conflict with another custom node...

**Comment by jia66** [comment]
the same error, javascript console (f12）see that:

Uncaught (in promise) ReferenceError: structuredClone is not defined
    at analyse_graph (use_everywhere.js:24)
    at async ComfyApp.queuePrompt (app.js:2044)

**Comment by chrisgoringe** [comment]
Please check comfy is up to date.

**Comment by JakeTheSnake3p0** [comment]
I just updated everything and I'm still getting no joy. Browser console output below:

> menu_auto_nest.js:21 just pass through.
> rgthree.js:302 [rgthree] There was an error queuing nodes 574 TypeError: Cannot read properties of undefined (reading '1')
>     at use_everywhere.js:55:94
>     at Array.forEach (<anonymous>)
>     at use_everywhere.js:46:26
>     at Array.forEach (<anonymous>)
>     at analyse_graph (use_everywhere.js:40:51)
>     at async ComfyApp.queuePrompt (app.js:2044:16)
>     at async app.queuePrompt (rgthree.js:328:17)
>     at async app.queuePrompt (nodeMenu.js:54:13)
>     at async l.queuePrompt (InstallMissingModelsButton-ak7be-3i.js:1:2721)
>     at async Rgthree.queueOutputNodes (rgthree.js:298:13)
> queueOutputNodes @ rgthree.js:302
> await in queueOutputNodes (async)
> callback @ menu_queue_node.js:21
> inner_onclick @ litegraph.core.js:13935
>

**Comment by chrisgoringe** [comment]
Thanks, that's really helpful output. Looks like there is a compatibility issue with rgthree - I'll look into it.

**Comment by JorgeR81** [comment]
I already had rgthree, before installing cg-use-everywhere.
They both are working, but after using F12, I noticed rgthree throws a lot of errors, in UE workflows.
I'm not sure if it's related. 

The errors in the workflow go away, if I use the rgthree link fixer.
But if I run the workflow again and save the image, they will show up again in the new image workflow.

![f12](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/00fe25d6-1fd4-4eec-8e06-5327965fdb65)

**Comment by chrisgoringe** [comment]
Can I check if this is still an issue? The original report was "Cannot queue anymore" - is that the case?

Also - was this with an old workflow (loaded from an image)? There is a known historical issue with the graph saved in the image having the UE links recorded as links but not in the nodes, which I'm pretty sure got resolved.

**Comment by JakeTheSnake3p0** [comment]
After updating everything, I had to recreate some nodes from scratch which ultimately lead to a working state. Thank you for the update!
