### ISSUE TITLE
Styles for UE? text boxes

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#118]
See https://github.com/chrisgoringe/cg-use-everywhere/issues/111#issuecomment-1980702202

**Comment by JorgeR81** [comment]
About the styling,

See if you can also do something about the mute and the bypass states.

![bps](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/dba37d1c-2713-4323-ba3b-1a62993432ed)

**Comment by chrisgoringe** [comment]
Done - including the bypass state - in 4.7.3 just pushed.

**Comment by JorgeR81** [comment]
Looks good !

I have some issues when I change the color multiple times. 
These color issues in EU? nodes are fixed, most of the times, when toggle bypass, on and off, to change the style.

But this may also be related to Comfy UI issues.
For 2 or 3 weeks now, I've had color issues in vanilla nodes ( the ones with 2 tones ) when I select back the "No color" option, as you can see in the images.

Although toggling bypass does not fix the Comfy UI global issue.
Also, the UE? issue happens only sometimes, so it's harder to reproduce, while the global issue happens every time. 

I've opened an issue there, for the global issue.
https://github.com/comfyanonymous/ComfyUI/issues/2904

I've also seen workflow images from other people, with the same issues, recently. 

![colors](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/baca42bf-a089-468b-9a52-5da7353a4049)

![color2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/48454e7e-8099-4da6-bc98-538adc34db26)
