### ISSUE TITLE
hello, how to send to multi group at one time?

### ISSUE THREAD

**Issue by K-O-N-B** [chrisgoringe/cg-use-everywhere#120]
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/152141077/871719b9-5e9d-4a4d-be9f-475a2f6926ef)

doesn't work like this.

**Comment by chrisgoringe** [comment]
The fields are regular expressions. You can find out a lot about regexes, and test to see what they do and don't match [here](https://regex101.com/) (the quick reference in the bottom right-hand corner is fantastic).

In this particular case: if you want to match any group with a '1' or a '2' in the name you can just put `[12]` (square brackets in regular expressions mean 'any of these symbols'). 

Hope that helps!

**Comment by K-O-N-B** [comment]
this is very helpful for a beginer, thank you!
