### ISSUE TITLE
Nodes are no longer sending to other nodes

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [chrisgoringe/cg-use-everywhere#121]
I just updated the nodes, and now the everywhere nodes aren't working.

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/52193044/cc25dbd9-afc4-4bb2-8251-5fbe952e5a81)

**Comment by GalaxyTimeMachine** [comment]
I just rolled back to commit d9582c7fd878dd96d51b2684b4b2ae71bd601cc5 and that works, so it was commit 02355efc4494254240d1c5b20c9c58c4d318f543 that broke it.

**Comment by niko2020** [comment]
same issue here

**Comment by chrisgoringe** [comment]
Yeah - sorry,  I did a bad commit. Should be fixed now if you update.

**Comment by chrisgoringe** [comment]
@niko2020 @GalaxyTimeMachine - should be fixed now. Apologies.

**Comment by freeleafcn** [comment]
Now it works again. Thanks

**Comment by niko2020** [comment]
fixed now. thanks for quick update!

**Comment by GalaxyTimeMachine** [comment]
Thanks! :)
