### ISSUE TITLE
[Bug] Freezing when bypassing Anything Everywhere? autocomplete

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-use-everywhere#123]
Hi, thanks for implementing autocomplete in your node! It's really useful!

But I just found a "serious" bug when you bypass `Anything Everywhere?` in this mode.
The workflow completely freeze: can't move around, zoom or interact with nodes. 

https://github.com/chrisgoringe/cg-use-everywhere/assets/161304036/f227cf41-225c-463c-891e-563a8beea0f0

To unfreeze you have to go to settings, disable autocomplete and refresh the page.

**Comment by chrisgoringe** [comment]
Oh, that's bad. Thanks, I'll look at it!

**Comment by JorgeR81** [comment]
I think this bug was introduced after the initial implementation of autocomplete.

I tested bypass and it worked before.
This was before the new styling of the UE? node.

I even have the created png images with bipassed UE? nodes in the workflow.
But when I load them now, the GUI also freezes.

**Comment by JorgeR81** [comment]
I  now remember bypass was also working, after the new style changes for UE? autocomplete.
I even posted some images here. 
https://github.com/chrisgoringe/cg-use-everywhere/issues/118#issuecomment-1985507851

**Comment by JorgeR81** [comment]
This is odd !

I recreated the previous workflow with the bypassed UE? node and it works, as you can see in the image.
For this, I used a version of the same workflow, also created on march 7, but in which the UE? node was not bypassed.

But when I load the original workflow, with the bypassed UE? node, created on march 7, it freezes, as I stated before.

And, If I take the bypassed workflow that's working right now : ...
* Delete the bypassed UE? node;
* Add a new UE?, to replace the deleted node, exactly the same;
* Then if bypass the new UE? node, the workflow will also freeze


![test001b](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/a6277499-6e84-4824-b5f1-39ab7a31d03b)

![test001](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/11ca09cb-c3dd-4921-aae2-6e89c4aaff14)

**Comment by chrisgoringe** [comment]
Believe fixed in 4.7.5

**Comment by JorgeR81** [comment]
It seems to be working. 
I can even load that workflow, from March 7, with the bypassed EU? node.
