### ISSUE TITLE
Can't change color back to "no color" on any node

### ISSUE THREAD

**Issue by andygock** [chrisgoringe/cg-use-everywhere#124]
After installing this, on all my nodes, I can change the color like normal,but it fails to change back to "no color".

Problem goes away after disabling or uninstalling this custom node.

ComfyUI Revision: 2055 [a9ee9589] | Released on '2024-03-09'

v4.7.6

Screenshot below:

![everywhere-color-issue](https://github.com/chrisgoringe/cg-use-everywhere/assets/555418/e05362f3-6f18-465e-b5ac-ac47df385acd)

**Comment by chrisgoringe** [comment]
thanks for finding this! Will look into it.

**Comment by JorgeR81** [comment]
I also had this issue, but I thought it was a Comfy UI issue. 
After this fix, it seems to be solved for me.

But, I still have the other color issue, specific to the UE? nodes.
I mentioned both issues here.
https://github.com/chrisgoringe/cg-use-everywhere/issues/118#issuecomment-1985507851
