### ISSUE TITLE
Problem with primitive node since "node proxy" commit

### ISSUE THREAD

**Issue by Danamir** [chrisgoringe/cg-use-everywhere#125]
Since the commit 4037fc923be4be977938c9b66b4ffbf9e97773c7, all my primitives nodes are invalid.

**Can be reproduced by** : 

 - Loading the default ComfyUI Workflow
 - Converting the KSampler "seed" to input
 - Adding a "utils/primitive" node
 - Trying to connect the node to KSampler

This will result in this instead of connecting (the second line is still attached to the mouse cursor) : 

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/15424198/bd427f2d-6a2e-4161-b0b2-8b5991600581)

The render will not run, as the seed is still None : 

```
Prompt outputs failed validation
KSampler:
    - Failed to convert an input value to a INT value: seed, None, int() argument must be a string, a bytes-like object or a real number, not 'NoneType
```

If you try to reload the workflow, this error will be displayed : 

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/15424198/5059a649-8916-47dc-b5fa-f5c350082e52)

**Temporary fix** :  

Checkout the previous commit with : 

```bash
git checkout a4b8ed196f48e6cea009bafd98f0f2abb4875aec
```

**Comment by Danamir** [comment]
Tested with only cg-use-everywhere in custom_nodes, the problem is still present. So it does not seem to be an incompatibility with another custom node.

Note : I'm at ComfyUI commit `65397ce601030c9f5934b0b277a019bdaa911a5f` .

**Comment by JeffreyBull76** [comment]
Same issue, plus use everywhere breaks all my text inputs. I can still type in them but they become blanked out while typing (making them unusable essentially) Only way to fix my workflows is disabling this node. Currently the node breaks all my workflows (sadly cause its a great node)

**Comment by chrisgoringe** [comment]
I've just pushed a new update which I think resolves many, if not all, of these issues. Please let me know if it doesn't!

**Comment by Danamir** [comment]
Yes, everything is back to normal on my side, thanks !

This really make me think I ought to make a script to store all the commit id of my custom nodes at some point, kind of pip freeze. 😅
