### ISSUE TITLE
m1 Error while importing workflow

### ISSUE THREAD

**Issue by yiwangsimple** [chrisgoringe/cg-use-everywhere#127]
![截屏2024-03-11 12 56 56](https://github.com/chrisgoringe/cg-use-everywhere/assets/121092793/1701af6c-cb03-494e-8d3c-9fe45f5ad8ce)
m1 Error while importing workflow

**Comment by yiwangsimple** [comment]
Delete the js file mentioned in the error report, and you can read the json file normally.

**Comment by chrisgoringe** [comment]
please update and check if you still have the problem

**Comment by yiwangsimple** [comment]
> please update and check if you still have the problem please update and check if you still have the problem

still have the problem. 
[workflow.json](https://github.com/chrisgoringe/cg-use-everywhere/files/14554435/workflow.json)

**Comment by chrisgoringe** [comment]
OK, I've just pushed an updated that fixes at least part of the problem. There may still be another issue, but I'm not sure if it is with UE nodes or something else. Please see what happens for you now.

**Comment by yiwangsimple** [comment]
> OK, I've just pushed an updated that fixes at least part of the problem. There may still be another issue, but I'm not sure if it is with UE nodes or something else. Please see what happens for you now.

现在可以正常导入了，但是这个节点未能正常显示，不过还是非常感谢
![Uploading 截屏2024-03-11 15.41.25.png…]()

**Comment by yiwangsimple** [comment]
![Uploading 截屏2024-03-11 15.41.25.png…]()

**Comment by yiwangsimple** [comment]
![Uploading test.png…]()

**Comment by yiwangsimple** [comment]
![Uploading test.png…]()

**Comment by chrisgoringe** [comment]
That latest comment looks like it has an image attached, but it isn't there - so I don't know what the current problem is!

**Comment by yiwangsimple** [comment]
![Uploading test.png…]()

**Comment by laoliu1023** [comment]
Delete the node and download it from a new one,

**Comment by yiwangsimple** [comment]
https://i.postimg.cc/fRV2RYPR/test.png

**Comment by yiwangsimple** [comment]
> That latest comment looks like it has an image attached, but it isn't there - so I don't know what the current problem is!

https://i.postimg.cc/fRV2RYPR/test.png

**Comment by chrisgoringe** [comment]
OK, that's saying you are missing some custom nodes. Nothing to do with UE.

**Comment by yiwangsimple** [comment]
> OK, that's saying you are missing some custom nodes. Nothing to do with UE.
Okay, thanks again.
