### ISSUE TITLE
Multi Line Text fields are blank when editing

### ISSUE THREAD

**Issue by jandolina** [chrisgoringe/cg-use-everywhere#128]
Since the last update, my multi-line text fields go blank when I try to edit them. If I disable the Use Anywhere nodes, the text fields start working again. Do any of you have a fix or workaround. These nodes are kinda rad and I would like to keep using them. 

![Screenshot 2024-03-11 at 8 50 58 AM](https://github.com/chrisgoringe/cg-use-everywhere/assets/21065646/bd299ff8-bb6c-4173-b5ae-d4384844b604)

**Comment by ricperry** [comment]
Can confirm. Disabling Use Everywhere fixes this problem. It's every multi-line text input field.

**Comment by doggeddalle** [comment]
Reinstalled comfy due to this. Reinstalling UE and using and it all works, so not convinced it was entirely this, maybe something in combination with it.

**Comment by jandolina** [comment]
Can confirm, uninstalling and reinstalling this collection fixes the problem

**Comment by chrisgoringe** [comment]
I saw this happening briefly, but can't now reproduce it.

**Comment by JorgeR81** [comment]
I just noticed I had this issue too. 

But it was fixed after updating all, via Comfy UI Manager.
No need to reinstall.

**Comment by jandolina** [comment]
Thank you!
