### ISSUE TITLE
The UE? node fields disappear on mouse click, with autocomplete enabled. 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-use-everywhere#129]
This is after the latest update.
It only happens when I click on a UE? field, with autocomplete enabled. 

![bug2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/c9448552-ad0b-4a48-89bc-90286a59bbcb)

**Comment by chrisgoringe** [comment]
Anything in the javascript console (f12)?

**Comment by chrisgoringe** [comment]
Ah - I've reproduced. No idea why yet, but can confirm it's a real thing!

**Comment by chrisgoringe** [comment]
Weird. It seems to happen the second time I click one of the fields, but not the first...

**Comment by JorgeR81** [comment]
For me, it happens every time, on click up.

**Comment by JorgeR81** [comment]
> Weird. It seems to happen the second time I click one of the fields, but not the first...

I also have that behavior if I click the on triangle arrow, in the right corner of the field. 

When I click for the first time, the arrow is gone, but the fields are still visible.

**Comment by chrisgoringe** [comment]
OK - see if it's fixed now. There are some unfortunate decisions deep in the litegraph core code that need to be worked around!

**Comment by JorgeR81** [comment]
The latest fix is working for me.
