### ISSUE TITLE
Need an extension node to change the name of the input to better receive "Anything Everywhere?"

### ISSUE THREAD

**Issue by hiowenluke** [chrisgoringe/cg-use-everywhere#131]
Anything Everywhere is great, thank you!

I am creating a workflow with many of nodes, and I ran into a problem with Anything Everywhere.
As shown in the picture below:

<img width="989" alt="image" src="https://github.com/chrisgoringe/cg-use-everywhere/assets/19872828/31977cc4-e229-4167-a11a-3d51018a99b7">

There are multiple image inputs, belonging to nodes and groups with no regular names, and completely different functions, that require lengthy regular expressions or set nodes colors to match them (which makes the workflow look cluttered with colors).

I wish there was a more elegant way.

For example, in the recipient's image input, extend a node to assign a new name for it ( similar to Get in  https://github.com/kijai/ComfyUI-KJNodes) , then specify the same input name in "Anything everywhere?", as shown below:

<img width="1046" alt="image" src="https://github.com/chrisgoringe/cg-use-everywhere/assets/19872828/753a4fc3-4a5b-4379-bd8a-ba49ec34e5be">

Or am I missing something, or do you have a better idea?

Thanks.

**Comment by hiowenluke** [comment]
I can not find the way. Do you have any idea?

**Comment by chrisgoringe** [comment]
Right click on the input. It’s a bit fiddly, you need to get the right
spot, but then it comes up on the right click menu

**Comment by hiowenluke** [comment]
I tried so many times before, and I could get familiar with almost every pixel on the menu.
But I couldn't find the way to rename it.

<img width="443" alt="image" src="https://github.com/chrisgoringe/cg-use-everywhere/assets/19872828/b2321d42-b065-441d-9942-93137bd21553">
