### ISSUE TITLE
Simplify the UE? autocomplete layout

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-use-everywhere#134]
The UE? node looks good now.
But I think the design is more complex than what's necessary, which could increase the probability of bugs.

Can't you just use the original ( vanilla ) fields ?
Do you really need to redraw some different fields on top of the node ?

If this is just to show the triangle arrow facing down, on mouseover, I don't think it's necessary.
And if the balloon arrow don't exactly match each vanilla field height position, just remove the arrow part from the balloon.

![flds](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/ab8f81a3-e2d1-4f37-aa59-d373859f9195)

We also don't have this for the vanilla fields, and it's OK.
We don't have a visual indicador, when we mouseover vanilla fields. 
And when we click on a vanilla field and see the input textbox, we are supposed to know the field where we clicked, to which the textbox refers to.

![flds2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/10829fe4-4311-4cd6-b0a8-648eb1218b02)

These UE? custom features are nice, but will never be a perfect match for the rest of Comfy UI visuals.
For instance, the custom fields are still in front of the input textbox.

![flds3](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/1ffeb628-8c3d-4922-a595-6a87a4b4000a)

**Comment by chrisgoringe** [comment]
> Can't you just use the original ( vanilla ) fields?

Not really. The original fields are ComfyUI Text Widgets, not HTML elements. The autocomplete uses the built-in HTML tools rather than writing a custom one - so it greatly reduces the danger of bugs :).

That said, it might be possible to use the text edit popup (not at all sure of that). If not, I can at least add a visual indication of the field being edited.

**Comment by JorgeR81** [comment]
OK, I see.
The vanilla text edit popup is still usable.
You just need to move the workflow a bit, to get the custom fields out the way.

**Comment by chrisgoringe** [comment]
Take a look at it now and see what you think

**Comment by JorgeR81** [comment]
This is an extra click, but I actually like it more this way. 

It gives larger text to type. 
I think it allows a better interaction between typing ( or deleting characters ) and the autocomplete options that became available. 

But, it's the final goal to get rid of the custom fields ?
They are still in the front of their own front textbox, sometimes. 

![test1](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/c064bf59-17ed-4923-aa73-88c91f314f37)

**Comment by chrisgoringe** [comment]
That’s weird. I’ve never seen that happen!

**Comment by JorgeR81** [comment]
For me, it only seems to work when the UE? nodes are not highlighted.
Or if the highlight is on a different node. 

![test4](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/48b755fd-98c7-4f3a-b7c2-e90c33f00013)

**Comment by chrisgoringe** [comment]
Take a look now. 

Incidentally, it looks like there is an underlying Comfy issue here as well:

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/4a88b7a4-a5c7-42d7-8d46-67499cb98f60)

**Comment by chrisgoringe** [comment]
I'm going to close this issue and will open more specific ones for any outstanding issues.
