### ISSUE TITLE
Anything Everywhere + Seed (rgthree) Seems to work, but the seed input is not highlighted.

### ISSUE THREAD

**Issue by Jamerrone** [chrisgoringe/cg-use-everywhere#135]
I think that this is actually working fine as I seem to get a new seed for every generation + the seed is embedded in the image but for whatever reason the seed input it is not highlighted. Also, if I display the UE links, they do not animate unless I move around, kinda weird but not breaking.

**Comment by JorgeR81** [comment]
Are you using Anything Everywhere + Seed (rgthree) together ?
That would be nice ! 
But I get an error ...

```
Error occurred when executing Seed Everywhere:

SeedEverywhere.func() got an unexpected keyword argument 'INT'

File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

![seed](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/4023c6db-f306-4dcc-aadf-de3d14629e66)

**Comment by JorgeR81** [comment]
OK, I see it works using a UE? node !

The seed input is highlighted, but it just looks different for the seed's darker color input. 

![seed2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/b39df1b2-c4d8-4b82-b7e3-26c3ada39f73)

**Comment by JorgeR81** [comment]
All connected !

![all](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/ccb038c3-eb92-4d47-a4be-ff092f1b8437)

**Comment by Jamerrone** [comment]
Yeah... it works fine, it just throws me off that the input color is lost. I also do not use the animated links, I just wanted to see how everything is connected, but I couldn't because it did not render any links, just a bunch of dots that only move around if I pan the camera.

Wait, did I just call the window camera?...

**Comment by JorgeR81** [comment]
Can't you see the UE links ?
Only the dots ?

![links](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/f004b461-2a30-4611-95a9-87a6610f2337)

**Comment by JorgeR81** [comment]
If I press SHIFT the dot animation also works.

**Comment by Jamerrone** [comment]
I think that my issue is that I have changed the link's render mode to straight. That last update actually fixed the issue partially. I can now see the connections, but the dots are still rendered as if the link render mode was set to its original value.

**Comment by JorgeR81** [comment]
I have this too ! 
I never tried that before, so I don't know if it ever worked properly ...

![str](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/72f48f84-c17d-47fa-92bc-e80beacf859e)

**Comment by chrisgoringe** [comment]
The fact that the inputs weren't highlighted when links are visible was a dumb bug, should now be fixed. I've created a new issue for the dots being in the wrong place (this never worked!) #136 and for the animation dots not moving #137.

**Comment by JorgeR81** [comment]
>  inputs highlighted when links are visible

Yes it's working. 
Quite useful to help distinguish the UE? links. 

By the way, can you change the color scheme, for the pale green links ?
( like I did for "sampler" in the edited image ) 

![edit](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/503771b7-b2c9-4d06-87c3-18b102c0d282)

**Comment by chrisgoringe** [comment]
Sorry, I can't immediately see what change you made?

**Comment by JorgeR81** [comment]
The input dot for the pale green wires is grey / black.
It would look better, if the input dot was also pale green.
I edited the image for the "sampler" input dot, to see how it would look.

**Comment by chrisgoringe** [comment]
I'm going to leave that one, at least for now.
