### ISSUE TITLE
Spurious text box still appears sometimes

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#138]
See https://github.com/chrisgoringe/cg-use-everywhere/issues/134#issuecomment-1996135848

**Comment by chrisgoringe** [comment]
It still shows up in some scenarios:

**_If a minimized UE? node is cloned._**
In this case it goes away when the node is maximized.
It never shows up again, even if the node is minimized again.
This is a minor issue, since the cloned UE? node needs to be maximized anyways, to make connections.
If I reload the page, and then pan / zoom the worflow a bit, it also goes away.

**_If I copy UE? nodes ( Crtl+C ), even if maximized._**
If I reload the page, and then pan / zoom the worflow a bit, it also goes away.

**_If save a template with UE? nodes, even if maximized._**
If I reload the page, and then pan / zoom the worflow a bit, it also goes away.

**_If I load a template with minimized UE? nodes._**
It's also fixed by maximizing and minimizing all of them, but it's a bit more annoying.
If I reload the page, and then pan / zoom the worflow a bit, it also goes away.

**_If I open a worflow with minimized UE nodes._**
This only happens sometimes and it goes away if I pan / zoom a bit.
No need to reload the page in this case.

**Comment by chrisgoringe** [comment]
@JorgeR81 
Are you happy to test a branch? 
If so - take a look at `more-ui-fixes`

I think the above issues are resolved, and #142 almost completely resolved.

**Comment by JorgeR81** [comment]
Sure, but how do I enable this ?

**Comment by chrisgoringe** [comment]
In the console go into the custom-nodes/cg-use-everywhere directory

Then type:

git pull

(to make sure everything is up to date)

Then

git switch more-ui-fixes

To go back,

git switch main

**Comment by JorgeR81** [comment]
> It still shows up in some scenarios:

If a minimized UE? node is cloned. -- _**FIXED**_

If I copy UE? nodes ( Crtl+C ), even if maximized. -- _**FIXED**_

If save a template with UE? nodes, even if maximized. -- _**FIXED**_

If I load a template with minimized UE? nodes. -- _**_FIXED_**_

If I open a worflow with minimized UE nodes. -- _**still can happen, but very rare**
**It only seems to happen the first time the workflow is loaded, after you open Comfy UI.**
**And in this case it goes away without needing to reload the page, as I mentioned before.**_

**Comment by chrisgoringe** [comment]
Merged. I'm going to close this, the last point doesn't seem worth the worry.
