### ISSUE TITLE
display bug

### ISSUE THREAD

**Issue by K-O-N-B** [chrisgoringe/cg-use-everywhere#140]
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/152141077/c4c7eced-e9f7-4d6e-bd13-20cda6cdf3ed)

when I mouse click the group:
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/152141077/2bfe3d7c-e0e5-43b1-a555-4542a0d71343)

**Comment by JorgeR81** [comment]
I don't have the ComfyUI-Easy-Use theme, which uses transparency in all nodes. 
https://github.com/yolain/ComfyUI-Easy-Use

But it's probably related to this issue. 
https://github.com/chrisgoringe/cg-use-everywhere/issues/141

**Comment by JorgeR81** [comment]
OK, I see what's going on here.
The input fields from the UE? node are gone.
( There is another minimized UE? node behind that, but that's a different node. )

I also had something similar at some point, where the UE? fields were gone, but it was fixed a few updates ago. 

@K-O-N-B, was this fixed after the last update ?
( I've been wanting to try ComfyUI-Easy-Use )

**Comment by K-O-N-B** [comment]
the bug was fiexed.
