### ISSUE TITLE
UE? text boxes can appear in front of the edit box of other nodes

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#142]
See https://github.com/chrisgoringe/cg-use-everywhere/issues/139#issuecomment-1998606086

**Comment by JorgeR81** [comment]
OK, I think I'm on the test branch already.

This issue seems to be fixed. 

![branch](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/c652a50a-070c-472e-8ed3-47091cb6fe63)

**Comment by chrisgoringe** [comment]
Fix merged.
