### ISSUE TITLE
UE node in group node fails if the UE node inputs are group inputs

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#144]
Why you'd want to....

**Comment by JorgeR81** [comment]
I thought you meant this:

A grouped node with UE links, connected to another grouped node. 

But it works for me.

The only issue I notice, it's not related to UE
It's the preview disappearing from the [ Ksampler + Vae ] node after the image is finalized.
But that's actually a positive point for me. It's less distracting, without a duplicated image.

![group](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/3722940a-f51d-4d0d-8831-f6421011faf9)

**Comment by chrisgoringe** [comment]
The issue here is if a UE node is it of a group node, but the node feeding into it isn't - so the link into the UE node becomes an input to the group node.

That doesn't work.

**Comment by JorgeR81** [comment]
> Why you'd want to....

![group001](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/1a2ad0b9-d608-4e01-911a-af7549cdcf1a)

![test001](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/590423cf-ba2c-4d61-9d02-c049fcae1578)

But, @LukeG89's use case is more realistic ...

![test2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/7ba04f62-8173-401e-b4f3-0818a6bed4f0)

![group2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/fd50032e-e477-4c84-9fb5-de279a1252af)

**Comment by chrisgoringe** [comment]
You know about the “Prompt Everywhere” node in the pack?

**Comment by LukeG89** [comment]
I think @JorgeR81 meant the ability to merge more UE nodes together, to create something like "custom `Anything Everywhere3` nodes" but with the possibility of more connections if you merge more than 3 UE? nodes (for example). Is that just impossible?

At the moment this operation just breaks all UE connections, not only the merged nodes ones.

**Comment by JorgeR81** [comment]
> You know about the “Prompt Everywhere” node in the pack? Designed for exactly this? (LukeG's case)

Yes, I would only use 2 UE? nodes for conditioning at a "second stage", to take advantage of node priorities. 

In this example, if I mute or remove the ControlNet group, the workflow still works, without needing to make any additional changes, because the conditioning links form  [ Prompt Everywhere ] at the "first stage" are redirected automatically.

![cond](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/2cbe029d-2600-4c7c-aced-08ba0c6c1cff)

**Comment by JorgeR81** [comment]
> I think @JorgeR81 meant the ability to merge more UE nodes together, to create something like "custom Anything Everywhere3 nodes" but with the possibility of more connections if you merge more than 3 UE? nodes (for example).

Yes, if possible that would be nice. 
When you have a lots of them it could save some space.

![nodes](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/94677b71-92a8-4898-b6a9-5298dbc4022d)

**Comment by JorgeR81** [comment]
On the subject of optimizing space, could you also reduce the minimum height of the UE? node, to match the vanilla nodes.
After you made the custom fields closer to each other, in a previous issue, the minimum height stayed the same. 
This is also a low priority, of course. 

![size](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/c08344e6-60a0-4513-8e40-7abb4904e11b)

**Comment by JorgeR81** [comment]
There is a workaround for this, with the "pass" nodes, from this pack !

https://github.com/aegis72/aegisflow_utility_nodes

![aegis1](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/68b35ba0-2121-490e-8a61-b45ac918cd00)

![aegis](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/2423c6c3-7f93-4499-a0db-9fc681dc1bee)

![aegis2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/d5320cc5-39b5-4b08-9114-195592b5ec28)

**Comment by JorgeR81** [comment]
It also works with multiple types of inputs:

![aegis3](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/254e701a-ca2b-4ff6-b45d-f33716771eb0)

![aegis4](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/61d3b78f-d315-4a38-ab2e-828971148910)

**Comment by JorgeR81** [comment]
Multi pass ! 

![mp2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/1a8bd727-3fc7-4b8b-b3e8-7d2587725c9d)

![mp1](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/ad44b223-fed1-4851-a521-624645af54d2)

**Comment by LukeG89** [comment]
That's a trick! But at this point I think it would be easier to merge the custom node with the UE and then hide all UE widgets in the Group nodes Manager

https://github.com/chrisgoringe/cg-use-everywhere/assets/161304036/f27e4a5b-da5d-4fa9-9dd5-9d6df9815f23

If this method will be optimized, it will be the best choice

**Comment by JorgeR81** [comment]
It would be really useful to add simple string nodes to the grouped node. 
But this breaks the UE connections ... 

![string](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/fe722c90-86db-46cc-9045-a12b18c4fd62)

![str2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/9393ca33-b221-43f4-adb7-af4f3578a4f6)

**Comment by JorgeR81** [comment]
> merge the custom node with the UE and then hide all UE widgets in the Group nodes Manager

But if you are going to hide the regex widgets, why not just use the basic UE node for the grouping ?

![str7](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/01fcecb1-9910-4c4b-aa6e-8077234b5fc2)

![str6](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/a037320c-dfbc-49ad-b4b4-63dcbf19a58a)

**Comment by LukeG89** [comment]
> But if you are going to hide the regex widgets, why not just use the basic UE node for the grouping ?

Beause it keeps the specific custom connections that you choose (mine was just an example)

**Comment by JorgeR81** [comment]
Yes, for me the "input_regex" could stay hidden most of the time.

![str8](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/7aa1ac20-e81b-4a93-a9dc-f94c95c0e283)


I'd just like to be able to add simple string nodes to the group, to use the same widgets for all the grouped UE? nodes.

![str10](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/bfcb3685-710c-4e33-b452-801deb7f443a)

![str12](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/64338ff9-a4eb-4030-b93d-e7a3a903ec3c)
