### ISSUE TITLE
[ feature ] add option to show UE links only for highlighted nodes

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-use-everywhere#145]
The option to show individual UE links on mouseover is very useful, for complex workflows.

But I need to always disable it in the settings, after using it, because it can be a little distracting, during normal Comfy UI use. 

Can you add an option to display individual UE links only for highlighted nodes ?

This way it will work only on mouse click ( to highlight the node ), so it would be more controllable. 

In this example I'm seeing the UE link because of mouseover.
But it could also be triggered by node highlighting, and the visual result would be the same.  

![hl](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/73cea99f-f089-4856-8b24-5fcf72454ff3)

In this case it will work even better, because now if I try to change the regex, the UE link is hidden, since the mouse pointer is no longer on the UE node. 

![hl2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/837048cc-88b2-42ab-958b-40cfd93b3d20)

**Comment by chrisgoringe** [comment]
Added in 4.7.13

![Screenshot 2024-03-17 213941](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/644df39b-dc48-4504-b878-26fc6e053066)

**Comment by JorgeR81** [comment]
Only one small issue.

Now, after changing the visualization option, in the settings or the right click menu, I have to click any node for the wire drawing to update.

**Comment by chrisgoringe** [comment]
Can you give me steps to reproduce that? I don't seem to have the problem.

**Comment by JorgeR81** [comment]
If I use the right click menu to show / hide links, nothing happens.  

I need to click on a node or on the workflow for the option to update ( e.g. to hide or show the links ).

**Comment by JorgeR81** [comment]
This was fixed after the last update.
