### ISSUE TITLE
[ feature ] option to disable UE? links for nodes inside the same group

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-use-everywhere#147]
Normally, I use regular links inside groups, and UE? nodes to make connections between groups.

It would be easier to prevent loops, if there was an option to disable EU? links, for nodes inside the same group.

In this example, I have a ControlNet group.
Since it uses UE? nodes it has priority over the [ Prompts Everywhere ] node ( image 1 ).
So, to disable ControlNet, I just need to mute the group ( image 2 ).
This works very well !

But to send conditioning to all other groups in the workflow, and prevent a loop, I need to use multiple UE? nodes ( image 1 ).
I'd like for this to work, with the same UE? node sendind to all groups, without creating a loop ( image 3 )

This would also be useful, if I want to save the ControlNet group as a template.
This way the template would be compatible with more workflows, without modifications. 

----

**Image 1** - to prevent a loop, I need to use a set of UE? nodes ( positive and negative ) for each set of groups in the workflow, 
( e.g. all groups with the prefix/name "Sampler"and "Upscalers" )

![group](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/8f3b47a2-387b-475f-99cc-5ae6cd5eb36b)

----

**Image 2** - I just need to mute the group to disable ControlNet ( the priorities are great ! )

![group3](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/d4516532-c3cb-43f2-8db7-fbf13a9894a3)

----

**Image 3** - If I use a single set of UE? nodes to send to all groups in the workflow, I also create a loop.

![group2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/312fd213-3f81-4e9b-8c70-0986c7519638)

**Comment by JorgeR81** [comment]
I just noticed you already have a setting to do the opposite thing : `Send only within my group(s)`

Can you add this other setting to the right click menu, for each node ?

I was thinking about a global setting, but this would be even better !

**Comment by JorgeR81** [comment]
And the restriction stays on, even if I load the nodes as a template ! That's great ! 

I also have the [ aegisflow_utility_nodes ] which creates a group for the template, when it's loaded.
https://github.com/aegis72/aegisflow_utility_nodes

So I just need to load the template and it will be connected automatically. 
( I Just need another UE in the workflow to connect the image ).

![cnt](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/90ec0e12-6dd6-4703-b0db-89b9344df7d0)

**Comment by chrisgoringe** [comment]
Take a look at the latest update - has options for group and color to 

- send to all
- send only to matching
- send only to not matching

See if that's what you need!
