### ISSUE TITLE
[Bug] A compatibility issue with Custom Scripts makes text disappear

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-use-everywhere#151]
After disabling your custom node, I found the main cause of a bug that was bothering me for months.

I think there is a compatibility issue between UE and `pythongosssss/ComfyUI-Custom-Scripts`.

I have reported this issue on another custom node (workspace manager), because I thought it was causing the problem:
https://github.com/11cafe/comfyui-workspace-manager/issues/245#issue-2172534709

This is the specific bug: https://github.com/11cafe/comfyui-workspace-manager/issues/245#issuecomment-1985621736

The bug goes away only if I disable Custom Scripts or UE.

**Comment by JorgeR81** [comment]
I have [ ComfyUI-Custom-Scripts ] but not [ comfyui-workspace-manager ]

I never noticed that issue.

Maybe it's also an interaction with another node.
See if you have something I don't:

- ComfyUI_Noise
- cg-use-everywhere
- ComfyUI_ADV_CLIP_emb
- ComfyUI_Cutoff
- ComfyUI_TiledKSampler
- ComfyUI_IPAdapter_plus
- ComfyUI-Custom-Scripts
- ComfyUI_UltimateSDUpscale
- rgthree-comfy
- ComfyUI_essentials
- aegisflow_utility_nodes
- comfyui_controlnet_aux
- ComfyUI-Inspire-Pack
- ComfyUI_smZNodes
- ComfyUI_InstantID
- ComfyUI-Manager
- comfyui-reactor-node
- ComfyUI-Impact-Pack
- was-node-suite-comfyui

**Comment by LukeG89** [comment]
@JorgeR81 Thanks for your help!
It's hard to say, I have a ton of nodes installed... 😅 

Excluding yours, this is what I also have:

- ComfyMath
- ComfyUI_Dave_CustomNode
- ComfyUI_experiments
- comfyui_face_parsing
- ComfyUI_FizzNodes
- ComfyUi_NNLatentUpscale
- ComfyUI_Preset_Merger
- comfyui_segment_anythings
- ComfyUI-Advanced-ControlNet
- comfyui-animatediff
- ComfyUI-AnimateDiff-Evolved
- ComfyUI-AutomaticCFG
- ComfyUI-bleh
- ComfyUI-Crystools
- ComfyUI-FBCNN
- ComfyUI-Flowty-LDSR
- ComfyUI-Frame-Interpolation
- ComfyUI-HQ-Image-Save
- ComfyUI-Image-Matting
- ComfyUI-Image-Selector
- comfyui-inpaint-nodes
- ComfyUI-InstructIR
- ComfyUI-LLaVA-Captioner
- ComfyUI-Marigold
- ComfyUI-post-processing-nodes
- comfyui-propost
- ComfyUI-RAVE
- ComfyUI-SDXL-EmptyLatentImage
- ComfyUI-VideoHelperSuite
- comfyui-workspace-manager
- ControlNet-LLLite-ComfyUI
- efficiency-nodes-comfyui
- facerestore_cf
- image-resize-comfyui
- masquerade-nodes-comfyui
- sd-dynamic-thresholding
- sdxl_prompt_styler
- stability-ComfyUI-nodes
- StableZero123-comfyui

I can exclude the most recent ones from the list, but I can't remember when this bug has started popping out.
I don't even know what could be the cause, but for some reason UE is involved.

At least it's not an important issue, even though you can have an heart attack when your prompt has suddenly disappeared! 😬

**Comment by LukeG89** [comment]
Just tried disabling every single node, one by one, remaining only with **Manager**, **Custom Scripts** and **UE**. 

But the bug is still present:

https://github.com/chrisgoringe/cg-use-everywhere/assets/161304036/241a9f19-cb63-479b-ad7a-c7ab881524b3


And as I said before, if I disable one of these two nodes, the bug is gone. I don't know why.

**Comment by JorgeR81** [comment]
Maybe it's something in the settings in one of these nodes. 
This is what I have. 

![set](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/2255be2a-2f02-480f-bc64-b81bc6e169fb)

**Comment by LukeG89** [comment]
I already tried disabling everything, nothing changed 😞

**Comment by JorgeR81** [comment]
Try to uninstall 1 of these 2 and install again, instead of just disabling them.

**Comment by chrisgoringe** [comment]
Also worth going into ComfyUI/web/extensions and removing everything in there *except for core*. Do not delete core!

The old way of doing custom javascript (still used by many nodes) was to copy it into that folder. But then it often doesn't disappear even if the custom node is deleted. Then you find custom nodes can still do stuff even from the grave!

If you delete something that a custom node uses, it will put it back, so no harm removing it.

**Comment by chrisgoringe** [comment]
Also worth trying - look at the Javascript console after you've done the load that was broken (press f12) and see if there is a message of any sort hinting at the issue.

**Comment by LukeG89** [comment]
Tried everything you said: reinstalling both nodes, deleting folders from extension, also tried uninstalling other nodes that creates a folder inside extension (FizzNodes, Dave CustomNode and 3D Pose Editor), but didn't solve anything.

Here's the javascript console:
![javascript_console](https://github.com/chrisgoringe/cg-use-everywhere/assets/161304036/c43e08c1-ab69-43f5-a2da-235070af5d5b)

**Comment by LukeG89** [comment]
Here's the javascript console:
![javascript_console](https://github.com/chrisgoringe/cg-use-everywhere/assets/161304036/9ef5177f-19b3-4512-8016-9825473baabd)

**Comment by JorgeR81** [comment]
After so much trouble, you might as well try a new fresh install of Comfy UI.

That should fix it, for sure, right ?

Unless this is something related to your browser ...

**Comment by JorgeR81** [comment]
If you have the SSD space you could try a new portable install, without deleting the previous one.

I have 2 portable installs.
One of them only has "vanilla" functionally, and I use it as "backup".

**Comment by LukeG89** [comment]
For some reason the problem is gone, maybe an update fixed this strange issue.
