### ISSUE TITLE
Reduce the minimum size of UE? node, to match regular nodes.

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-use-everywhere#159]
Now that the custom widgets are closer to each other, the node can be smaller. 

![size](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/c08344e6-60a0-4513-8e40-7abb4904e11b)

**Comment by chrisgoringe** [comment]
Flagged as probably won't because I've been banging my head against the way ComfyUI DOM widgets work too much recently. But not closing, because maybe I'll come back to it.
