### ISSUE TITLE
Adding Simple String and UE to a group node breaks

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#160]

**Comment by JorgeR81** [comment]
I also noticed that when we have 2 grouped [ Simple String ] nodes, only the first output works.

![box1](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/c165a682-632f-41cd-a085-795e5d9383f2)
![box2](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/75a67bc8-2735-4bd9-a41e-3e6fe73345a4)

**Comment by chrisgoringe** [comment]
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/cd59eeb2-d6d2-44e5-b09d-23e405f753d3)

**Comment by JorgeR81** [comment]
This is working !

And I can also save the workflow, without freezing it.

But when I do that, the UE links are hidden, and the UE input dots are shown as disabled.  
This is just a visual issue; the workflow still works. 
And If I click the refresh button, in the browser, this is fixed.

**Comment by chrisgoringe** [comment]
Clarification - do the links disappear when you save? Or fail to appear when you reload?

**Comment by JorgeR81** [comment]
The links disappear when I save the workflow.

If I click the browser's refresh button, they show up again.

I opened a new issue for this.
