### ISSUE TITLE
Mention pass nodes in documentation

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#161]
https://github.com/aegis72/aegisflow_utility_nodes pass nodes can be used to get around the UE group node input issue

**Comment by JorgeR81** [comment]
By the way, these are also a workaround to allow bypassing nodes receiving UE links. 
https://github.com/chrisgoringe/cg-use-everywhere?tab=readme-ov-file#cautions

![lora1](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/e2462161-9bf8-4249-bbf5-ca63806cde2a)

**Comment by JorgeR81** [comment]
The node creator also made this workflow system based on UE? nodes:

https://www.youtube.com/@MajorStudioArt/videos

**Comment by JorgeR81** [comment]
I also tried pipe / bus nodes from other suites ( rgthree / WAS / Impact Pack  )
They all allow grouping UE? nodes.

But they all save these same 2 issues:

https://github.com/chrisgoringe/cg-use-everywhere/issues/166
https://github.com/chrisgoringe/cg-use-everywhere/issues/167

----
**rgthree** 

![rg3](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/c1fd638b-8efb-479a-95f2-c8ce3ac15d6d)

![rg30](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/fa4b790b-3dab-42ff-85d0-276dfa40da45)

----

**WAS**

![was1](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/81739c34-67be-4415-964c-f561e17074e0)
![was](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/6153e819-2382-48ee-ab7e-e6fc6fd577d0)

----

**Impact Pack** ( two node  pipe )

![imp](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/857d5215-e954-4aaf-81ed-d0559c37ce94)
![imp0](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/214f6225-7036-4a11-8ad5-e0f3d2ef609e)
