### ISSUE TITLE
Workflow freezes when saved, if pass nodes are included in group nodes. 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-use-everywhere#167]
If the workflow has a grouped node that includes a pass node, the workflow will freeze when it's saved.  

Clicking the refresh button in the browser fixes this. 

The saved json workflow seems to be fine.

Saving the workflow via saving the png image does not freeze the workflow.

**Comment by JorgeR81** [comment]
I also tried pipe / bus nodes from other suites ( rgthree / WAS / Impact Pack )
They all allow grouping UE? nodes.
But they also have this issue.

**Comment by JorgeR81** [comment]
After this fix ( https://github.com/chrisgoringe/cg-use-everywhere/issues/160 ), this issue also seems to be fixed.

But there is now the same minor issue, I described there:

When I save the workflow, the UE links are hidden, and the UE input dots are shown as disabled.  
This is just a visual issue; the workflow still works. 
And If I click the refresh button, in the browser, this is fixed.

**Comment by chrisgoringe** [comment]
Will follow up the visual issue in #160.
