### ISSUE TITLE
[Idea] Add prioritization to AE nodes that would otherwise conflict

### ISSUE THREAD

**Issue by DrJKL** [chrisgoringe/cg-use-everywhere#170]
(I'll try to put together an actual example later)

Right now, I think that if 2 AE? nodes would otherwise conflict, neither is selected and the input that would otherwise be targeted is considered empty.

## Use case
I have a workflow with multiple phases  
The phases are Grouped  
In each, the output image/latent is piped into an `Anything Everywhere?` node with the group target set to the subsequent groups.
Then, each `AE?` would have a strictly increasing priority

I can then use the r3 fast group muter to turn off phases
### e.g.
```mermaid
graph LR;
    A[Generate]-->B[Upscale];
    B-->C[Style];
    C-->D[Detail];
```
to
```mermaid
graph LR;
    A[Generate]-->C[Style];
    C-->D[Detail];
```
or

```mermaid
graph LR;
    A[Generate]-->B[Upscale];
    B-->D[Detail];
```

**Comment by JorgeR81** [comment]
I just made a similar proposal earlier today !

It's about the same core idea of having a sequence of groups connected by UE? nodes.

And being able to mute one group in the sequence ( with the rg3 node ) without breaking the sequence.

I have an example workflow, focused on conditioning. 

https://github.com/chrisgoringe/cg-use-everywhere/discussions/168

**Comment by chrisgoringe** [comment]
I think this is a good problem to solve - going to close this issue and suggest we discuss in #168

**Comment by chrisgoringe** [comment]
Push a simple solution. UE? nodes now have a 'priority boost' on the right-click menu,
