### ISSUE TITLE
"//" in multiline input causes strange behaviour when connected nodes highlighted

### ISSUE THREAD

**Issue by za-wa-n-go** [chrisgoringe/cg-use-everywhere#172]
When the connected nodes feature is turned on, there is a problem where the input cursor moves on its own when "//" is used in the text input area.

**Comment by chrisgoringe** [comment]
Please provide more information

**Comment by za-wa-n-go** [comment]
https://github.com/chrisgoringe/cg-use-everywhere/assets/118154415/ce09549c-b150-4592-a0ee-35f325e026db

**Comment by JorgeR81** [comment]
Yes, I can reproduce this. 

With "//" in the prompt, no matter where I click, the cursor always returns to the front of the text, after "FastNegative,".

If I disable "highlight connected nodes", it works again.

![sls](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/af82367a-6d7f-4b03-b81f-cc7db976dffc)

![hl](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/62225c1b-a485-4d2b-a295-83d24151e96c)

**Comment by chrisgoringe** [comment]
That is so weird. I'll dig into it! Does // have some special meaning? Maybe to another custom node? I've never used it.

**Comment by za-wa-n-go** [comment]
can disable the string written in a line prefixed with "//".

**Comment by za-wa-n-go** [comment]
<img width="676" alt="image" src="https://github.com/chrisgoringe/cg-use-everywhere/assets/118154415/7afcbfdf-2e92-4d94-afaa-d2b8c578f261">

**Comment by chrisgoringe** [comment]
Thanks. Didn't know that!

**Comment by PsiClone99** [comment]
I am facing the same issue when adding { } to the prompt box, it jumps to the last word, once the parenthesis is removed, it works normal.
