### ISSUE TITLE
[Bug?] No connections if more than one Anything Everywhere node with color restriction

### ISSUE THREAD

**Issue by HWiese1980** [chrisgoringe/cg-use-everywhere#176]
Hey there,

I've run into a snag with the cg-use-everywhere custom node while using it in my project. Everything's been smooth sailing until I tried to set up a color restriction on a second "Anything Everywhere" node. Once I do that, all my "Anything Everywhere" connections just stop working. Here's a bit more detail:

What I'm using:

ComfyUI version: 2086[2f93b9](2024-03-26)
Browser: Chrome 123.0.6312.59 (Offizieller Build) (arm64)
OS: MacOS 14.4.1 (23E224)
What's going wrong:

I set up an "Anything Everywhere" connection with the cg-use-everywhere node, no problem.
Then, I add another one of these nodes and give it a color restriction.
Boom, all my connections break. No errors, no warnings, they just stop working.
What I expected:
I was hoping each node would do its own thing, not mess with the others. Like, I set a color on one node, and everything else keeps running smoothly.

What I tried:

Redoing the connections, which fixes things until I add another color.
Restarting everything, clearing cache, the usual stuff – no dice.
Is this a known thing? Any workarounds or fixes would be super helpful. Really digging using this, so hoping there's a simple solution I'm missing.

Cheers!

**Comment by JorgeR81** [comment]
I'm on Windows 10.
On a simple workflow it works for me, as you can see.

<details>
<summary>show image</summary>
<IMG src="https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/e1e56633-afff-4eb4-98a9-a14f9fa18898"  alt="image.jpg"/>
</details>


But, I noticed a similar issue. 
If the UE node with color restriction, also has a group regex, all UE connections break.

<details>
<summary>show image ( issue )</summary>
<IMG src="https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/bbd3082c-a75c-40db-bfef-105164d5ff1a"  alt="image.jpg"/>
</details>

**Comment by HWiese1980** [comment]
> I'm on Windows 10. On a simple workflow it works for me, as you can see.
> 
> show image
> But, I noticed a similar issue.  If the UE node with color restriction, also has a group regex, all UE connections break.
> 
> show image ( issue )

Ah, yeah, that's possible. @chrisgoringe is this something that can be fixed? Sounds like a bug to me.

**Comment by HWiese1980** [comment]
:-) Appreciated, @chrisgoringe!
