### ISSUE TITLE
UE Nodes breaks Efficient Nodes

### ISSUE THREAD

**Issue by gonzalu** [chrisgoringe/cg-use-everywhere#182]
Hello,

I noticed that the UE Nodes package causes one of the functions of the Efficient Nodes package to break. The RANDOM SEED function gets reset immediately after pressing random. 

Problem only occurs after installing UE nodes. 

Thank you for looking into it if possible

P.S. I also posted on the Efficient Nodes (JAGS111) GitHub Repo

https://github.com/chrisgoringe/cg-use-everywhere/assets/32348862/a769ad7a-b848-41f6-bb3b-fada31830e81

**Comment by BliNDF123** [comment]
I mentioned this issue back in February, but a mistake on my part of an 'Everywhere' node which I was using wrong which he tells me this and doesn't say anything about the same issue you've recorded here which I also described.  You've probably noticed you can click on any node, not only UE nodes and Efficiency nodes, all of them.  I was just TRYING Seed Everywhere, and that's what seemed to bug mine out.  Click anywhere in the ComfyUI window now and it will keep doing a random seed, very annoying, had to uninstall at that point as it was unusable.

**Comment by chrisgoringe** [comment]
Hi, I've just posted a fix (I believe) for this issue. Update the UE nodes and try again.

**Comment by novaexe** [comment]
> Hi, I've just posted a fix (I believe) for this issue. Update the UE nodes and try again.

confirmed fixed

**Comment by chrisgoringe** [comment]
Could you look at the JavaScript console (f11) and see if there are any error messages?

**Comment by gonzalu** [comment]
So sorry for the delay in responding, Chris. 

Looks like it may have been a fluke... I literally cleared the workspace and loaded a new workflow to do something else, and lo and behold, the christmas lights and the magic glowing circles were back ... go figure. 

P.S. functionality never suffered... it was still sending stuff through the workflow it was just the visuals. 

Maybe it just needed a kick.
