### ISSUE TITLE
Strict undefined check in `is_UEnode` not handling null.

### ISSUE THREAD

**Issue by rgthree** [chrisgoringe/cg-use-everywhere#184]
Came across this. Sometimes `node_or_nodeType.type` is `null` (not `undefined`) which causes an issue in this code in `use_everywhere_utilities.js`.

```javascript
// in use_everywhere_utilities.js
function is_UEnode(node_or_nodeType) {
    var title = node_or_nodeType.type;
    if (title===undefined) title = node_or_nodeType.comfyClass;
    if (title===undefined) return false;
    return (title.startsWith("Anything Everywhere") || title==="Seed Everywhere" || title==="Prompts Everywhere")
}
```

This method seems to run on construction of a ComfyNode where `node_or_nodeType.type` is always undefined always. However, a bunch of rgthree-nodes this is actually `null` and this breaks becuase of the `title.startsWith`. This isn't currently invoked but I was playing with the idea of better alignment with the default ComfyNode, which would allow this to run on these rgthree nodes.

I'm still trying to figure out why type is always undefined in ComfyNode and null in these rgthree nodes, but I would still consider this a bug as null could make it through to that startsWith call.

By looking at this, my recommendation would be to change the two `title === undefined` to `tile == null` (with two equals) which will match both undefined and null.

**Comment by rgthree** [comment]
FWIW, I took a look at why there's the difference between null and undefined with ComfyUI and some rgthree-nodes.

Turns out, LiteGraph sets [type to null explicitly](https://github.com/comfyanonymous/ComfyUI/blob/258dbc06c34ebf723ae17fa23207407e2e05fad1/web/lib/litegraph.core.js#L2446) when it's instantiating a new LGraphNode, and rgthree-nodes extend LGraph correctly.

Turns out, ComfyNodes don't actually extend LiteGraph's nodes, so never call into the LGraphNode constructor and, thus, type is left undefined. So, if anything, the high level feels like this is buggy behavior in ComfyUI's ComfyNode for not actually being an LGraphNode.

I don't feel like hacking or working aroundf LiteGraph's LGraphNode constructor, since that feels like the right thing. What this means is if I do submit the change to allow other custom nodes to run `nodeCreated` for rgthree-nodes, this `is_UEnode` will throw an error for title being null. Nothing negative should happen, just errors in the console.

**Comment by chrisgoringe** [comment]
huh. Nice find. Cleaned it up like this to avoid the whole null/undefined thing completely:

```js
function is_UEnode(node_or_nodeType) {
    const title = node_or_nodeType.type ?? node_or_nodeType.comfyClass;
    return ((title) && (title.startsWith("Anything Everywhere") || title==="Seed Everywhere" || title==="Prompts Everywhere"))
}
```

I never really got my head around javascript truthiness :)
