### ISSUE TITLE
[Bug] Conflict between tiny terra v2 and UE

### ISSUE THREAD

**Issue by novaexe** [chrisgoringe/cg-use-everywhere#187]
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/69226867/82390e8c-cc38-4179-b021-70b3ba8fbf55)
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/69226867/a8775349-10b9-4c54-9094-c6f6908cb893)
when tiny Terra is present anywhere on the workflow it disables UE's graphic's, the nodes are still connected, this is a visual bug

**Comment by chrisgoringe** [comment]
Hopefully fixed by @TinyTerra ; pls update and check.

**Comment by novaexe** [comment]
> Hopefully fixed by @TinyTerra ; pls update and check.

yep confirmed fixed
