### ISSUE TITLE
it shows "anything" when I drag it out.  Why?

### ISSUE THREAD

**Issue by ericlee2023** [chrisgoringe/cg-use-everywhere#199]
I used this node, but why doesn't it display the corresponding node names like in the official demo? Instead, it shows "anything" when I drag it out.
<img width="559" alt="Snipaste_2024-06-21_11-57-12" src="https://github.com/chrisgoringe/cg-use-everywhere/assets/133652787/f70fa05c-7de1-428c-8d61-cece60c4c2c5">
<img width="367" alt="Snipaste_2024-06-21_11-59-01" src="https://github.com/chrisgoringe/cg-use-everywhere/assets/133652787/3fda9e07-09af-4e01-8b82-c3f42c8eb343">

**Comment by chrisgoringe** [comment]
Thanks for reporting this - I'll check it out! Can you look at the JavaScript console (f11) and see if there are any errors being reported?

**Comment by ericlee2023** [comment]
There are no error messages here. This is the photo from before dragging the node, and this is the photo from after dragging the node. There are no prompts in the background.
<img width="1610" alt="beform" src="https://github.com/chrisgoringe/cg-use-everywhere/assets/133652787/e95b92ee-0446-426a-b73f-b01fa1142cce">
<img width="1445" alt="aftor" src="https://github.com/chrisgoringe/cg-use-everywhere/assets/133652787/69ac7474-c5d1-4968-a53b-c01b92268dee">

**Comment by zhai-hello** [comment]
Is your problem solved, I'm having the same issue

**Comment by ericlee2023** [comment]
no

**Comment by chrisgoringe** [comment]
Apologies all, been flat out with real life. I hope to look at this soon!

**Comment by chrisgoringe** [comment]
I can't reproduce - this is what happens for me:
![GIF 1-07-2024 3-40-20 PM](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/7eda628d-ccce-45f3-bdd0-4059b8483cfd)
Please check the *javascript* console (by pressing f11 on your browser) - the screenshots you sent before are the server console - and look for errors. I suspect there is an interaction with another custom node.

**Comment by GalaxyTimeMachine** [comment]
I had the same problem and it was because there were two of these nodes in the same workflow, so they clash with each other.

**Comment by chrisgoringe** [comment]
Please share workflow and try f11 for errors. I use multiple copies all the time without trouble so there must be some other issue

**Comment by GalaxyTimeMachine** [comment]
If you have two prompt everywhere nodes they will clash, because the node doesn't know which one to use.

**Comment by chrisgoringe** [comment]
But there is no reason for that to cause the issue being observed, which is inputs being named 'everything' even when connected.

There are, incidentally, many ways to get around the clash you describe (group restrictions, colour restrictions, UE? nodes)

**Comment by zhai-hello** [comment]
同一台电脑，我另外装了一个comgyui，只下载了这个节点，发现节点没有问题，可以正常显示model，clip，vae等。我经常用的comfyui 装了很多节点，就不能正常显示，链接时候，只显示anything。应该是节点之间有冲突，但是，我不知道怎么调用浏览器代码，发到这里来。我能看到有很多代码，但是不知道应该发哪些。所以，想问一下，能不能把这个节点的优先级调到最高，这样如果有冲突的时候，节点不再受影响。
以下是翻译软件翻译的话：
On the same computer, I install another Comfyui and only download this node. I found that there was no problem with the node and it could display models, clips, vae, etc. normally. The Comfyui I often use has many nodes installed, but it cannot display properly. When linking, it only displays' anything '. There should be a conflict between nodes, but I don't know how to call the browser code and send it here. I can see a lot of code, but I don't know which one to send. So, I would like to ask if it is possible to set the priority of this node to the highest, so that if there is a conflict, the node will no longer be affected.

**Comment by chrisgoringe** [comment]
Please press f11 on your web browser, and look for any errors showing in the JavaScript console.

It is not possible for me to change the priority of the nodes.

Alternatively, you could add the custom nodes you use to the new install a few at a time, and see which ones cause it to stop working

**Comment by zhai-hello** [comment]
is this？
import { app } from "../../scripts/app.js";
import { GraphAnalyser } from "./use_everywhere_graph_analysis.js";
import { LinkRenderController } from "./use_everywhere_ui.js";
import { convert_to_links, remove_all_ues } from "./use_everywhere_apply.js";
import { has_priority_boost } from "./use_everywhere_utilities.js";

function main_menu_settings() {

    app.ui.settings.addSetting({
        id: "AE.details",
        name: "Anything Everywhere show node details",
        type: "boolean",
        defaultValue: false,
    });
    app.ui.settings.addSetting({
        id: "AE.autoprompt",
        name: "Anything Everywhere? autocomplete (may require page reload)",
        type: "boolean",
        defaultValue: true,
    });
    app.ui.settings.addSetting({
        id: "AE.checkloops",
        name: "Anything Everywhere check loops",
        type: "boolean",
        defaultValue: true,
    });
    app.ui.settings.addSetting({
        id: "AE.showlinks",
        name: "Anything Everywhere show links",
        type: "combo",
        options: [ {value:0, text:"All off"}, {value:1, text:"Selected nodes"}, {value:2, text:"Mouseover node"}, {value:3, text:"Selected and mouseover nodes"}, {value:4, text:"All on"}],
        defaultValue: 0,
        onChange: app.graph.change.bind(app.graph),
    });      
    app.ui.settings.addSetting({
        id: "AE.animate",
        name: "Anything Everywhere animate UE links",
        type: "combo",
        options: [ {value:0, text:"Off"}, {value:1, text:"Dots"}, {value:2, text:"Pulse"}, {value:3, text:"Both"}, ],
        defaultValue: 3,
        onChange: app.graph.change.bind(app.graph),
    });
    app.ui.settings.addSetting({
        id: "AE.stop.animation.running",
        name: "Anything Everywhere turn animation off when running",
        type: "boolean",
        defaultValue: true,
        onChange: app.graph.change.bind(app.graph),
    });    
    app.ui.settings.addSetting({
        id: "AE.highlight",
        name: "Anything Everywhere highlight connected nodes",
        type: "boolean",
        defaultValue: true,
        onChange: app.graph.change.bind(app.graph),
    });
    app.ui.settings.addSetting({
        id: "AE.replacesearch",
        name: "Anything Everywhere replace search",
        type: "boolean",
        defaultValue: true,
    });
}

function submenu(properties, property, options, e, menu, node) {
    const current = properties[property] ? (properties[property]==2 ? 3 : 2 ) : 1; 
    const submenu = new LiteGraph.ContextMenu(
        options,
        { event: e, callback: inner_function, parentMenu: menu, node: node }
    );
    const current_element = submenu.root.querySelector(`:nth-child(${current})`);
    if (current_element) current_element.style.borderLeft = "2px solid #484";
    function inner_function(v) {
        if (node) {
            const choice = Object.values(options).indexOf(v);
            properties[property] = choice;
            LinkRenderController.instance().mark_link_list_outdated();
        }
    }
}

const GROUP_RESTRICTION_OPTIONS = ["No restrictions", "Send only within group", "Send only not within group"]
function group_restriction_submenu(value, options, e, menu, node) {
    submenu(node.properties, "group_restricted", GROUP_RESTRICTION_OPTIONS, e, menu, node);
}

const COLOR_RESTRICTION_OPTIONS = ["No restrictions", "Send only to same color", "Send only to different color"]
function color_restriction_submenu(value, options, e, menu, node) {
    submenu(node.properties, "color_restricted", COLOR_RESTRICTION_OPTIONS, e, menu, node);
}

function priority_boost_submenu(value, options, e, menu, node) {
    const current = (node.properties["priority_boost"] ? node.properties["priority_boost"] : 0) + 1;
    const submenu = new LiteGraph.ContextMenu(
        [0,1,2,3,4,5,6,7,8,9],
        { event: e, callback: function (v) { 
            node.properties["priority_boost"] = parseInt(v);
            LinkRenderController.instance().mark_link_list_outdated();
        }, 
        parentMenu: menu, node:node}
    )
    const current_element = submenu.root.querySelector(`:nth-child(${current})`);
    if (current_element) current_element.style.borderLeft = "2px solid #484";
}

function node_menu_settings(options, node) {
    options.push(null);
    if (has_priority_boost(node)) options.push(
        {
            content: "Priority Boost",
            has_submenu: true,
            callback: priority_boost_submenu,
        }
    )
    options.push(
        {
            content: "Group Restrictions",
            has_submenu: true,
            callback: group_restriction_submenu,
        }, 
        {
            content: "Color Restrictions",
            has_submenu: true,
            callback: color_restriction_submenu,
        },
        {
            content: "Convert to real links",
            callback: async () => {
                const ues = await GraphAnalyser.instance().analyse_graph();
                convert_to_links(ues, node.id);
                app.graph.remove(node);
            }
        }
    )
    options.push(null);
}

function canvas_menu_settings(options) {
    options.push(null); // divider
    options.push({
        content: (app.ui.settings.getSettingValue('AE.showlinks', 0)>0) ? "Hide UE links" : "Show UE links",
        callback: () => {
            const setTo = (app.ui.settings.getSettingValue('AE.showlinks', 0)>0) ? 0 : 4;
            app.ui.settings.setSettingValue('AE.showlinks', setTo);
            app.graph.change();
        }
    },
    {
        content: "Convert all UEs to real links",
        callback: async () => {
            if (window.confirm("This will convert all links created by Use Everywhere to real links, and delete all the Use Everywhere nodes. Is that what you want?")) {
                const ues = await GraphAnalyser.instance().analyse_graph();
                LinkRenderController.instance().pause();
                convert_to_links(ues, -1);
                remove_all_ues();
                app.graph.change();
            }
        }
    });
    if (GraphAnalyser.instance().ambiguity_messages.length) {
        options.push({
            content: "Show UE broadcast clashes",
            callback: async () => { 
                alert(GraphAnalyser.instance().ambiguity_messages.join("\n")) 
            }
        })
    }
    options.push(null); // divider
}

export { main_menu_settings, node_menu_settings, canvas_menu_settings }
![Snipaste_2024-07-16_17-58-40](https://github.com/user-attachments/assets/a9144296-0a72-4859-8afb-f7e02330e190)

**Comment by chrisgoringe** [comment]
No, after you press f12 (sorry, not 11!), you need to locate the “console”
and look there

**Comment by zhai-hello** [comment]
I restarted Comfyui, and before restarting, I connected a wire called VAE. After restarting, the connected VAE can be displayed, but when I connect other wires, it still looks like anything. As can be seen from the picture, one displays VAE and the other displays anything
![Uploading Snipaste_2024-07-16_18-46-17.jpg…]()

**Comment by zhai-hello** [comment]
![Uploading Snipaste_2024-07-16_18-46-17.jpg…]()

**Comment by chrisgoringe** [comment]
Closing due to lack of response
