### ISSUE TITLE
(VHS incompatibility) A means to be notified of or opt out of use-everywhere connections.

### ISSUE THREAD

**Issue by AustinMroz** [chrisgoringe/cg-use-everywhere#201]
Recently, VHS added support for loading or saving videos directly from latents instead of images.
Under normal operation, the selection for images or latents is determined by whether or not a vae input is attached like so.

https://github.com/chrisgoringe/cg-use-everywhere/assets/4284322/27826e7b-2375-4a58-8261-8ed33cffef64

Unfortunately, I've only now realized this methodology is incompatible with cg-use-everywhere. Since onConnectionsChange isn't called,  the input does not swap type and latents are incorrectly produced instead of images at execution.
Is there a way for a node to either receive indication that a virtual link has been made with cg-use-everywhere or to otherwise opt out of being connected to by cg-use-everywhere?

**Comment by chrisgoringe** [comment]
Hmm. At present, no. But I think an input as "do not connect with UE" might be a good feature

**Comment by AustinMroz** [comment]
I've added a temporary workaround in VHS which wraps graphToPrompt after you do and deletes from the prompt any vae links to Load Video that do not exist in the graph itself.

It's a bit hackier than I would like, but suffices as an interim solution

**Comment by chrisgoringe** [comment]
OK. Perhaps if I added a check for an attribute called "before_ue_connects" which could be called (if found) to allow the node to reject a connection?

**Comment by AustinMroz** [comment]
That sounds great.

**Comment by chrisgoringe** [comment]
Adding the following code to `use_everywhere_graph_analysis.js` (line 85):
```
if (!is_connected(input) && !(node.reject_ue_connection && node.reject_ue_connection(input)))
```

So a custom node can define a method `reject_ue_connection` which takes the input object (from the `node.inputs` list) and can refuse the connection by returning something that evaluates as true. The method will only be called if the input is currently not connected.
