### ISSUE TITLE
JS serializeValue looping in another nodes

### ISSUE THREAD

**Issue by CosmicLaca** [chrisgoringe/cg-use-everywhere#202]
Hi, in other (not just mine) custom node front-end js of other developers if using `serializeValue` for example:

```
this.[variable].serializeValue = async (node, index) => {
     here looping the code of other nodepacks if your nodepack installed
}
```

the code within this function start looping if your nodepack installed, what is very inconvenient and unmanageable because the value of the variables defined inside the function is not stable, in many cases this affects seed integer generators where the variable takes a random value, but this does not have to be done every second. Would be good if the development not modify how other nodepacks working. :(

**Comment by chrisgoringe** [comment]
A possible fix for this is in development. It requires a significant change to the UE nodes, so testing may take a while.

**Comment by chrisgoringe** [comment]
Could you update and see if this now works as expected?
