### ISSUE TITLE
bug or wrong setting?

### ISSUE THREAD

**Issue by K-O-N-B** [chrisgoringe/cg-use-everywhere#206]
<img width="466" alt="image" src="https://github.com/user-attachments/assets/d65092f1-12a2-4eaf-aab6-fc87061d66b1">

the "model1" in model switch node has wire link, why the anything everywhere model node still link to it?
this make a loop error.

Loop (870,361,169,366,367) with broadcast (767) - not submitting workflow

**Comment by chrisgoringe** [comment]
Hmmm.

My guess is that the switch node makes it appear that the input model1 is unconnected even though it actually is. So UE is linking it up.

This is a compatibility issue with the other custom node.

I'll need to look into it.

**Comment by chrisgoringe** [comment]
In the new update there is an option to specify a node should never receive UE inputs (right click on the node). This might help!
