### ISSUE TITLE
Cannot read properties of undefined (reading 'inputs')

### ISSUE THREAD

**Issue by YMM0123456789** [chrisgoringe/cg-use-everywhere#208]
Brother, how can I solve this problem?
![CCA512DB9F497F446A7CFDBCE3218E98](https://github.com/user-attachments/assets/e0f2d9c3-0025-4eec-adc3-b5006f069821)

**Comment by chrisgoringe** [comment]
Please share the workflow

**Comment by YMM0123456789** [comment]
![微信截图_20240804130312](https://github.com/user-attachments/assets/72f6ffb5-a014-42f0-9881-226854e03399)
The issue has been resolved, there is a Convert to Group Node causing this problem
