### ISSUE TITLE
"Anything Everywhere?" values not broadcasting as expected

### ISSUE THREAD

**Issue by Gerkinfeltser** [chrisgoringe/cg-use-everywhere#209]
Thank you as always for UE! It helps so much to prevent excessive noodle soup setups. Unfortunately though, it seems some of the functionality has changed or broken as of late. (Not sure from what point as I haven't been using comfyUI for a few months).

"Anything Everywhere?" nodes used to broadcast floats & ints to the appropriately named inputs but do not seem to any longer. 
As you can see in the attached image, the "width" AE? should be paired to the Empty Latent's "width" input & the "upscale_factor" into the float_O's "upscale_factor" but no joy. Furthermore, reloading the comfyui page has no affect.
![image](https://github.com/user-attachments/assets/d90441ee-bc6d-4293-b3e0-55466bccf284)

**Comment by chrisgoringe** [comment]
The problem there is that the types don’t match. The node inputs expect
“INT” and “FLOAT”, but the UE nodes are receiving a generic numeric type
(as you can see from the input name)

I don’t think this has ever worked…

**Comment by Gerkinfeltser** [comment]
Hmmm, again due to my comfy usage absence I could be wrong but I swear I remember this working before. I was definitely able to broadcast values and width & height previously. One thing that seems to have changed (on the comfy side) is the input width & height nodules turned blue.

Thank you for the reply though, I'll continue to see if I can find a work around. 😄

**Comment by Gerkinfeltser** [comment]
Actually, that particular node didn't work when I ran the workflow. This one from impact does seem to though!
![image](https://github.com/user-attachments/assets/760f55ee-c0af-44c3-8df0-e681a643a4c8)
