### ISSUE TITLE
Can not see Toggle UE Link Visibility

### ISSUE THREAD

**Issue by trashie65** [chrisgoringe/cg-use-everywhere#21]
Updated UE pack, Updated Comfy, can not see Toggle UE Link Visibility when right clicking?
![UE](https://github.com/chrisgoringe/cg-use-everywhere/assets/45748708/67b60c36-627c-4381-a06e-dd6586596800)

**Comment by chrisgoringe** [comment]
Could you (a) post a workflow and (b) give me a list of custom nodes that you have loaded, so I can try to reproduce this?

**Comment by chrisgoringe** [comment]
Actually - first, try this:
- stop ComfyUI
- go into the ComfyUI directory and then into `web/extensions`
- delete the folders `cg-nodes`, `use_everywhere`, and any javascript files with use_everywhere names
- restart ComfyUI

I *think* that there might be a problem with old versions of the code hanging around... let me know if this helps, because I can put this into the installer if it fixes it.

**Comment by trashie65** [comment]
Hi after doing what you said the things that were not working are working ok now, the only problem i am having trouble with is condictioning Positive, i have 5 nodes that have positive input (all using the same positive prompt) 1 main Ksampler 1 Face Detailer 1 Hand detailer &  2 different upcalers, 
Can i just use 1 Anything Everywhere? and have the input_regex as positive or do i gave to have 5 seperate ones? as using one i am having problems that no pictures get generated after the Ksamplier... if i connect using the old noodles all are working?

**Comment by chrisgoringe** [comment]
Maybe you could post the workflow? It's hard to diagnose otherwise! 

Have you tried turning the UE link visibility on? That might help.

**Comment by trashie65** [comment]
Here is the workflow im working on rename . txt to json...
Custom Nodes used: Impack Pack, WAS node, ComfyUI_Comfyroll, Image chooser, UltimateSD upscale... ive removed some of the different type of prompting nodes to make things smaller for you, but the problem still happens.. please take a look. ive checked with UE link visibility on and everything looks connected
[Broken workflow.txt](https://github.com/chrisgoringe/cg-use-everywhere/files/12817368/Broken.workflow.txt)

**Comment by trashie65** [comment]
UPDATE Everthng is working great.. my problem as that the preview image after the Ksampler was out of order it started to show a preview image after it has been passed through other nodes with preview images and because i have a image chooser node the pauses the workflo it you cellect an image and press go it wass not letting the ksampler show the image... (hope this makes sence). The bottom line is IT WORKS... thank you for a great set of cutom nodes very useful...
