### ISSUE TITLE
装上这插件,生成功能失效.

### ISSUE THREAD

**Issue by OEIEE** [chrisgoringe/cg-use-everywhere#210]
装上这插件,进入网页界面,生成功能直接失效. queue prompt点击无效,试过很多版本,请作者修复.
comfyui整合包SD1.5

**Comment by shenyugub** [comment]
我也遇到了这个问题，查了下代码，作者对生成功能进行了重定义，会影响原功能
![1](https://github.com/user-attachments/assets/905cd443-020f-4c3e-a9a2-8dd0472fb77a)

**Comment by shenyugub** [comment]
希望作者修复一下这个问题

**Comment by chrisgoringe** [comment]
I'm sorry, but I'm woefully monolingual... I'll need that in English :)

**Comment by shenyugub** [comment]
Because of the modification of the code in the picture，in some cases, it will affect the execution of the queue prompt，the queue prompt does not respond after clicking.

**Comment by shenyugub** [comment]
I commented out the code in the picture, and then clicked the queue prompt to execute it normally.

**Comment by chrisgoringe** [comment]
Thanks. I’ve just uploaded an update, perhaps you could check it out?

If still a problem, let me know!

**Comment by chrisgoringe** [comment]
Also; when you click and the workflow does not submit, are there any errors
in the JavaScript console?

**Comment by shenyugub** [comment]
I have solved this problem.

In cg-use-everywhere/js/use_everywhere_graph_analysis.js，This error is "structuredClone is not defined".

I defined a function structuredClone:

function structuredClone(obj) {
  return JSON.parse(JSON.stringify(obj));
}

![1](https://github.com/user-attachments/assets/60a98fbd-fad6-4a17-b036-5fc59d6996f4)

**Comment by shenyugub** [comment]
I found the source of the problem.

In 'cg-use-everywhere/js/use_everywhere_graph_analysis.js', The error is 'structuredClone is not defined'

![1111](https://github.com/user-attachments/assets/77267f16-e26c-4f84-b2fb-450e1c57f3ac)

**Comment by chrisgoringe** [comment]
That will be because your browser or your ComfyUI is not up to date
