### ISSUE TITLE
"Anything Everywhere?" Not rendering inputs

### ISSUE THREAD

**Issue by M1kep** [chrisgoringe/cg-use-everywhere#214]
After updating Comfy today it seems the `Anything Everywhere?` nodes no longer render the input boxes for filtering.
![workflow(3)](https://github.com/user-attachments/assets/54155207-27ba-4054-a0a1-e82b857f8631)

**Comment by chrisgoringe** [comment]
Yes, just discovered the same.

**Comment by chrisgoringe** [comment]
This seems to be caused by the autocomplete code; it was a bit of a hack and I think the new Comfy front end expects cleaner custom widgets! I've disabled the autocomplete for the time being.
