### ISSUE TITLE
"Anything Everywhere?" is not displaying properly on the ComfyUI canvas

### ISSUE THREAD

**Issue by joelandresnavarro** [chrisgoringe/cg-use-everywhere#215]
@chrisgoringe "Is there something everywhere?" is not displaying correctly on the canvas after updating ComfyUI, however in the preview in node search the customization entries appear

![Captura de pantalla 2024-08-22 075326](https://github.com/user-attachments/assets/83e11ced-7dd2-4cb9-a39f-463f2f0eb846)
![Captura](https://github.com/user-attachments/assets/2f7c3f75-e0b4-4e5e-9d75-775ef6d0d375)

**Comment by hobojoker** [comment]
I'm seeing this same issue in the latest update

**Comment by chrisgoringe** [comment]
Please check you have latest version of UE, I pushed an update yesterday

**Comment by chrisgoringe** [comment]
See #214

**Comment by joelandresnavarro** [comment]
Correct, with the latest update it is fixed. Thanks!
