### ISSUE TITLE
Anything Everywhere3 not working

### ISSUE THREAD

**Issue by trashie65** [chrisgoringe/cg-use-everywhere#22]
It seems that Anything Everywhere3 is not picking up what is connect, so hence its not passed onto the relivent nodes in the workflow, connect to a normal Anything Everywhere node all ok.
![UE2](https://github.com/chrisgoringe/cg-use-everywhere/assets/45748708/4251109e-d922-4ca6-9260-672dd2b081b6)

**Comment by chrisgoringe** [comment]
Please see comment on #21

**Comment by chrisgoringe** [comment]
Believe this is now working?
