### ISSUE TITLE
Latest version of Comfy is breaking Anything Everywhere

### ISSUE THREAD

**Issue by CaptainGrock** [chrisgoringe/cg-use-everywhere#220]
Hi - in the latest version of Comfy, for some reason the Use Everywhere nodes (either single or 3) no longer register models and clips being sent in as models and clips causing workflows to lie dormant (attaching a sample JSON). This previously worked a few days prior to the update, so there may be something that's causing the model, clips, etc. to be recognized as generic items in Use Everywhere but end result-wise, the workflows or no longer executing (and they don't indicate that there's an error either - I only found this out by removing the Use Everywhere nodes and manually hooking things up). I LOVE your node, so thanks for helping to diagnose/fix.

[0830_1-NewLoader.json](https://github.com/user-attachments/files/16872974/0830_1-NewLoader.json)

**Comment by chrisgoringe** [comment]
Thanks for the report. 

I haven't had this problem, and it looks from your workflow like you are loading the models etc. using some custom nodes which I don't have? I will try to diagnose, but if you are able to let me know what loaders are connected to the UE nodes and not working it would help!

**Comment by CaptainGrock** [comment]
ok thanks, I've been using roughly the same set-up for months, but
generally for Flux, I'm using the UNET loaders (not a custom node) UNET
GGUF loaders ( GitHub - city96/ComfyUI-GGUF: GGUF Quantization support for
native ComfyUI models <https://github.com/city96/ComfyUI-GGUF>) - both of
them aren't working. I just tested and this seems to b happening for SDXL
loaders as well (standard checkpoint loader as well as Sampler Custom).
Thanks so much for your help!

**Comment by CaptainGrock** [comment]
Closing this issue - turns out there was an old additional copy in my custom_nodes folder for some reason.
