### ISSUE TITLE
Any chance for a AnythingEverywhere3 similar to powerlora?

### ISSUE THREAD

**Issue by defertoexpertise** [chrisgoringe/cg-use-everywhere#221]
Was wondering if theres any change you'd consider adding an anythingeverywhere3 but instead of 3 it could have unlimited links like how rgthree's power lora allows you basically just click ADD and you get a new input, theres many work flows that 3 works great but then theres some that i've got 4-5 in 1 area i'd love to be able to shove in but need to use 2 3's or a 3 and 2 1's ... feel like having a version thats flexible for any number would really clean the node options up want 2 inputs sure.. want 5.. done all on 1 node.

**Comment by chrisgoringe** [comment]
I did start looking at this, but the changes to the ComfyUI front end have thrown up issues that slowed it down. Hopefully!

**Comment by PrometheusDante** [comment]
I usually make group nodes for whichever amounts I need that work fine.
![workflow(4)](https://github.com/user-attachments/assets/087a3b64-2961-4eca-b6b5-57a137938f43)
[ue_group_node_example.json](https://github.com/user-attachments/files/17203307/ue_group_node_example.json)

However it does throw type mismatch errors that never caused any issues for me though. 
The only issue I ever had when experimenting with that was including the ue-nodes into a group node which provides the signal and sends at the same time. That did cause it to no longer work upon restarting Comfy.

> got prompt
> Failed to validate prompt for output 37:3:
> * (prompt):
>   - Return type mismatch between linked nodes: anything, LATENT != *
> * Anything Everywhere? 37:3:
>   - Return type mismatch between linked nodes: anything, LATENT != *
> Output will be ignored
> Failed to validate prompt for output 37:0:
> * (prompt):
>   - Return type mismatch between linked nodes: anything, MODEL != *
> * Anything Everywhere? 37:0:
>   - Return type mismatch between linked nodes: anything, MODEL != *
> Output will be ignored
> Failed to validate prompt for output 37:1:
> * (prompt):
>   - Return type mismatch between linked nodes: anything, CLIP != *
> * Anything Everywhere? 37:1:
>   - Return type mismatch between linked nodes: anything, CLIP != *
> Output will be ignored
> Failed to validate prompt for output 37:2:
> * (prompt):
>   - Return type mismatch between linked nodes: anything, VAE != *
> * Anything Everywhere? 37:2:
>   - Return type mismatch between linked nodes: anything, VAE != *
> Output will be ignored
> model weight dtype torch.float16, manual cast: None
> model_type EPS
> Using xformers attention in VAE
> Using xformers attention in VAE
> Requested to load SDXLClipModel
> Loading 1 new model
> loaded completely 0.0 1560.802734375 True
> Requested to load SDXL
> Loading 1 new model
> loaded completely 0.0 4897.0483474731445 True
> 100%|█████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.04it/s]
> Requested to load AutoencoderKL
> Loading 1 new model
> loaded completely 0.0 159.55708122253418 True
> Prompt executed in 11.08 seconds

Aside from that the only downside I found is that priority settings are lost on grouping unfortunately.

**Comment by chrisgoringe** [comment]
I'm not going to address issues related to group nodes. The underlying comfy implementation is very complicated to work with, and I suspect it is going to be re-written - but even if not, it's just not worth the work.

**Comment by PrometheusDante** [comment]
Yeah, absolutely. Group nodes are not very convenient to work with as of now and could do with some love. Especially rebuilding larger groups over and over for small changes, sorting everything, labeling, on/off-ing the in- and outputs... 
 
I would say that there is no real issue for ue-nodes there anyway. It just looks it when those type mismatch errors pop up, but they do not affect anything. It works nicely as is. 👌

Was more meant to be an answer to op's described case
