### ISSUE TITLE
Search after dragging out node is missing

### ISSUE THREAD

**Issue by Orenji-Tangerine** [chrisgoringe/cg-use-everywhere#224]
![image](https://github.com/user-attachments/assets/6f0857df-7f3b-4013-829b-ed29abc8a776)

![image](https://github.com/user-attachments/assets/bb8c6ba5-3af7-4c17-bed1-2621ced798b8)

I have been using it all these while and I think it is missing out of sudden or maybe after updating ComfyUI?

**Comment by chrisgoringe** [comment]
Duplicate of #219

This is due to the change in comfy front end
