### ISSUE TITLE
The anything everywhere? cannot set target, the panel disappear.

### ISSUE THREAD

**Issue by Jeff-goal** [chrisgoringe/cg-use-everywhere#225]
The previous workflow can work although the panel also disappear, but I cannot creat new workflow using anythingwhere? to set target.
![image](https://github.com/user-attachments/assets/28b080a3-f97b-4479-90c3-9cd99c094e53)

**Comment by Jeff-goal** [comment]
And I have tried unloading and reloading the plug-in

**Comment by chrisgoringe** [comment]
Could ensure that your install of UE is up to date? This issue occured a while back and I believe it to be fixed. See #214

**Comment by Jeff-goal** [comment]
It's OK now. I don't know why, but it worked after I restart the comfyUI this afternoon. Although I restarted several times this morning also - - Anyway, thanks a lot! Great work!
