### ISSUE TITLE
Prompt everywhere and FLUX

### ISSUE THREAD

**Issue by Aeitto** [chrisgoringe/cg-use-everywhere#226]
https://github.com/user-attachments/assets/d4be7446-69e3-4f9c-9314-7c2b08b5cd19

Hey, I either I'm doing something wrong in workflow or Prompt everywhere is not forking properly.
It only sends negative output to Xlabs Sampler.

**Comment by chrisgoringe** [comment]
Right "conditioning" (the name of the input) doesn't match the inbuilt regexs.

I will fix this - in the meantime you can click on the input dot and rename 'conditioning' to 'positive' and it should work.

**Comment by chrisgoringe** [comment]
It's basically a pair of regexes. The positive one matches 'positive', 'pos_' or 'prompt' or '正面'.
The negative matches 'neg_', 'negative' or '负面'

**Comment by Aeitto** [comment]
![image](https://github.com/user-attachments/assets/35a2a45f-2c60-4cd7-865e-c7d18ab50d2c)
Sadly I tried renaming everything and it dost work.

**Comment by chrisgoringe** [comment]
I don't understand. The unconnected input is still called "conditioning". That is what you need to rename.
