### ISSUE TITLE
Option to set UE node title to type on connection

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#230]

**Comment by chrisgoringe** [comment]
Maybe with "?" if UE?, and auto collapse

**Comment by ondrovic** [comment]
I recently ran into something similar and fixed it using the `Anything Everywhere?` node, here is a very basic example, maybe it will help with what you are doing?
![image](https://github.com/user-attachments/assets/2322a23f-9071-4693-b1ad-b4b179dd2c1a)

[anything_everywhere_fix.json](https://github.com/user-attachments/files/17148299/anything_everywhere_fix.json)

**Comment by PrometheusDante** [comment]
Personally I like naming them after the actual input_regex sent and keep them collapsed, while only naming them after the amount of signals when grouped
![workflow(1)](https://github.com/user-attachments/assets/a33a32e3-45a9-48eb-9f7e-4f3d0cd37eee)
