### ISSUE TITLE
Anything Everywhere? node is not detecting inputs and not connecting links

### ISSUE THREAD

**Issue by lchauvin** [chrisgoringe/cg-use-everywhere#234]
Hello,

I'm using Comfy v0.2.2 and before AE was working fine, but since then, node does detect the input and doesn't connect to anything (see screenshot)

![image](https://github.com/user-attachments/assets/9c153f1a-8bf4-40d7-b51a-65bd4722e52e)

**Comment by chrisgoringe** [comment]
I'm not having this issue. So it's probably an interaction with another custom node.

To help me reproduce, could you do these things, please?

Firstly press f11 on your browser and look in the console to see if there are any errors being reported, if so report them here

Secondly, give me a list of the other custom nodes you have installed (you can do this by going into you custom_nodel folder in explorer and giving me a screenshot or directory listing of what's there)

**Comment by lchauvin** [comment]
@chrisgoringe I'm getting a lots of these in the console

```
link list update failed
use_everywhere_utilities.js:25 TypeError: Cannot read properties of undefined (reading '0')
    at add_ue_from_node (use_everywhere_nodes.js:71:84)
    at use_everywhere.js:29:68
    at Array.forEach (<anonymous>)
    at LinkRenderController.analyse_graph [as the_graph_analyser] (use_everywhere.js:29:50)
    ```

**Comment by lchauvin** [comment]
Here is a list of my custom nodes:

![image](https://github.com/user-attachments/assets/8615d237-703f-4715-9747-d0aaf221e4fb)

**Comment by chrisgoringe** [comment]
Thanks, really helpful.

Do you have th emost up to date version of UE? Can you look in the Use-Everywhere folder, in the file `__init__.py`, and tell me what the line `UE_VERSION = ` has?

**Comment by lchauvin** [comment]
@chrisgoringe `UE_VERSION = "4.6.4"`

**Comment by chrisgoringe** [comment]
No, It isn't. 5.0.3 is the latest.

Possibly the issue is you seem to have renamed the folder? Don't know if that matters.

Can you go into the use everywhere folder and do 'git pull' and then restart comfy.

**Comment by lchauvin** [comment]
Now it works !! Thanks !!

I will check why it didn't update with the manager though !! :)
