### ISSUE TITLE
Seed Everywhere broken

### ISSUE THREAD

**Issue by Erehr** [chrisgoringe/cg-use-everywhere#24]
Queue Prompt stopped working after updating ConfyUI. Quick check of log and disabling all other extensions narrowed it to Seed Everywhere node. Other everywhere nodes works fine but with Seed Everywhere this is the error given:

```
use_everywhere.js:17 
Uncaught (in promise) DOMException: Failed to execute 'structuredClone' on 'Window': () => config could not be cloned.
    at analyse_graph (http://127.0.0.1:8188/extensions/use_everywhere/use_everywhere.js:17:13)
    at async ComfyApp.queuePrompt (http://127.0.0.1:8188/scripts/app.js:1624:16)
```

I noticed that all my nodes that had seed suddenly had both seed input and seed widget and had to be recreated to even work.

**Comment by chrisgoringe** [comment]
That last part is very weird - the seed everywhere node doesn't do anything to the nodes other than make a connection. 

However, I suspect this is related to the issue in https://github.com/comfyanonymous/ComfyUI/pull/1677 which has been resolved (2 hours ago) - so I hope a latest version of ComfyUI will work.

Could you check?

**Comment by Erehr** [comment]
It's working now after updating ComfyUI. Sorry for false alarm.
