### ISSUE TITLE
Loop error

### ISSUE THREAD

**Issue by Mackay031** [chrisgoringe/cg-use-everywhere#240]
hi, I am unable to run old workflows as I get this error:

Loop (377,375,390,364,370,374,373,359,358,357,356,355,353,354,384,228) with broadcast (387) - not submitting workflow

This is where I am using Anything Everywhere

![Screenshot 2024-10-17 at 19 19 22](https://github.com/user-attachments/assets/50edbb50-4937-40f7-8d10-d7970604c996)

Any thoughts? FYI, i havent used ComfyUI for a while and updated eveything last night. Now getting this error.

Thanks in advance

**Comment by Mackay031** [comment]
Here is the workflow that is having the issue if that helps? 
[workflow_loop_issue.json.zip](https://github.com/user-attachments/files/17440858/workflow_loop_issue.json.zip)

**Comment by chrisgoringe** [comment]
I don't have all those custom nodes... but it looks like you have a loop being made by a VAE. 

You can turn the loop checker off in the options, and see if it works. 

If you still have the problem, please repost a new issue.
