### ISSUE TITLE
Highlight setting causing lag (was Possible Bug? (UI Lagging))

### ISSUE THREAD

**Issue by AssassinsLament** [chrisgoringe/cg-use-everywhere#241]
So just yesterday, I started getting horrible lag on my comfyui.  First I thought it was my computer, but the odd thing was that I could move the comfyui  (chrome) window to a different monitor (i have three screens), and there would be no lag. Eventually, I figured out that it was the size of my main monitor's  resolution. My screen's resolution is 2560x1440... so I changed it to 1920x1080, and sure enough, no UI lag. Change it back, and lag again. 

I can even change the size of Chrome's window to a smaller size and it would stop the lag. Next I had to figure out if it was comfyui or one of the many nodes I installed. After reinstalling comfyui like 3 times, and fresh installing all the nodes... I finally installed everything and disabled the nodes all one by one... and the result was that Use Everywhere was the issue. 

Everytime I disabled it, no UI lag. Everytime I re-enabled it, there was lag again. When I say UI lag, i mean if I double click on the screen to bring up the search nodes menu, it comes up but if i type inside the search... comfy seems to lag and not be able to give me suggestions on the nodes. Also, even enabling fast bypass buttons would lag, selecting right click selections lagged, changing settings lagged. 

I'm not saying that it was this nodes doing, but something must have chanegd in comfyui to make it like this?

Does anyone else have this issue?

**Comment by chrisgoringe** [comment]
Do you have the UE link animations turned on? If so, try turning them off.

**Comment by AssassinsLament** [comment]
> Do you have the UE link animations turned on? If so, try turning them off.

Hey, thank you for the reply. I tested the animations and all the settings... and it turns out to be the "highlight" setting. I turned all the settings on except for the highlight one and no lag. The moment I turn it on, it lags. So it's definitely that one.

**Comment by chrisgoringe** [comment]
OK, thanks. I'll look into it.

**Comment by chrisgoringe** [comment]
Just pushed a small change which might well fix this for you.

**Comment by AssassinsLament** [comment]
> Just pushed a small change which might well fix this for you.

Seems to be working good now! Thank you for taking the time to fix it!
