### ISSUE TITLE
[ Bug ] I can't open old workflows

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-use-everywhere#242]
When I try to open an old worflow, the canvas is empty
I have many errors in the browser, all from loading a single workflow.

These workflows are quite complex but they always worked without any issues.
Think they were working, before the "wireless input" not being drawn, was fixed ( https://github.com/chrisgoringe/cg-use-everywhere/issues/238 )

![er1](https://github.com/user-attachments/assets/4fbc57a1-cfb7-4267-bfd3-af6e09c70706)

( ... a lot more similar errors in between ...  )

![er2](https://github.com/user-attachments/assets/ec8f2876-6f18-4de3-9a6d-f17ed41231fa)

**Comment by bux10** [comment]
Same problem here. the workflow was working last night, this morning I just get a blank canvas. Disabling 'Anything Everywhere' allows the workflow to load again. I get the same type of output in the console as the OP.

**Comment by JorgeR81** [comment]
It seems to be related to new new Frontend

The issue happens with the latest version ( 1.3.32 )

But not with the one that ships with ComfyUI ( 1.3.26 )

**Comment by chrisgoringe** [comment]
Just pushed 5.0.4 which I believe fixes this problem

**Comment by JorgeR81** [comment]
It seems to be fixed.
