### ISSUE TITLE
Latest update breaks a bunch of rgthree-comfy nodes

### ISSUE THREAD

**Issue by rgthree** [chrisgoringe/cg-use-everywhere#244]
Looks like the latest update breaks a lot of nodes in rgthree-comfym specifically the mode relays and repeaters.

**Comment by rgthree** [comment]
Looks like it's because of this new code:

```js
if (!node.__mode) {
    node.__mode = node.mode
    Object.defineProperty(node, "mode", {
        get: ( )=>{return node.__mode},
        set: (v)=>{node.__mode = v; node.afterChangeMade?.('mode', v);}            
    })
}
```

This is overwriting the `mode` property on the node cutting the node's original/previous property descriptor. Note, I have code in rgthree-comfy that should be a way to define properties while still persisting previous property descriptors:

```js
export function defineProperty(instance, property, desc) {
  const existingDesc = Object.getOwnPropertyDescriptor(instance, property);
  if (existingDesc?.configurable === false) {
    throw new Error(`Error: Cannot define un-configurable property "${property}"`);
  }
  if (existingDesc?.get && desc.get) {
    const descGet = desc.get;
    desc.get = () => {
      existingDesc.get.apply(instance, []);
      return descGet.apply(instance, []);
    };
  }
  if (existingDesc?.set && desc.set) {
    const descSet = desc.set;
    desc.set = (v) => {
      existingDesc.set.apply(instance, [v]);
      return descSet.apply(instance, [v]);
    };
  }
  desc.enumerable = desc.enumerable ?? existingDesc?.enumerable ?? true;
  desc.configurable = desc.configurable ?? existingDesc?.configurable ?? true;
  if (!desc.get && !desc.set) {
    desc.writable = desc.writable ?? existingDesc?.writable ?? true;
  }
  return Object.defineProperty(instance, property, desc);
}
```

And then you can call it similar to the original: 
```js
if (!node.__mode) {
    node.__mode = node.mode
    defineProperty(node, "mode", {
        get: ( )=>{return node.__mode},
        set: (v)=>{node.__mode = v; node.afterChangeMade?.('mode', v);}            
    });
}
```

**Comment by chrisgoringe** [comment]
Oh very neat! I will shamelessly copy that code!

**Comment by chrisgoringe** [comment]
Updated UE to 5.0.6 with this fix - hopefully that will make it work with rgthree again!

**Comment by chrisgoringe** [comment]
@rgthree just reading through the logic of your code - isn't there a problem if `desc.set` is not defined, but `existingDesc.set` is defined? It looks like the `existingDesc.set` doesn't get added to `desc`, so won't it be lost?

I always call with both get and set, so it won't arise, but...

**Comment by rgthree** [comment]
Good question! I'm pretty sure a property descriptor will call up the prototype chain for the getter/setters. But if either are overridden, then it can't (and there's no "super" call for an accessor, AFAIK)

**Comment by chrisgoringe** [comment]
wouldn't adding something like this work?

```js
  if (existingDesc?.set && !desc.set) {
    desc.set = existingDesc.set
  }
  if (existingDesc?.get && !desc.get) {
    desc.get = existingDesc.get
  }
```

**Comment by rgthree** [comment]
Just to test, it works correctly as above:

```js
var b = {};
defineProperty(b, 'test', {get: () => console.log('1 - get'), set: () => console.log('1 - set')});
defineProperty(b, 'test', {get: () => console.log('2 - get'), set: () => console.log('2 - set')});
defineProperty(b, 'test', {get: () => console.log('3 - get')});
defineProperty(b, 'test', {set: () => console.log('4 - set')});

b.test = 4;
// 1 - set
// 2 - set
// 4 - set
// 5 - set

b.test
// 1 - get
// 2 - get
// 3 - get
// 5 - get
```

However, there may be a slight bug in the `writable` condition. It should probably be `if (!desc.get && !desc.set && !existingDesc.get && !existingDesc.set) {` in the case no get/set were passed, but there is a get/set defined on the existing.

**Comment by chrisgoringe** [comment]
that last bit would be dealt with by placing the extra lines right at the end?
