### ISSUE TITLE
Conflict with latest Comfy GUI update

### ISSUE THREAD

**Issue by jeffufu** [chrisgoringe/cg-use-everywhere#246]
Hello!

I accidentally updated to the latest ComfyUI GUI https://blog.comfy.org/comfyui-v0-3-0-release/ and noticed suddenly my workflows wouldn't display correctly—they were being loaded and my menu/settings worked, but the actual nodes/nodes wouldn't display correctly.

I was able to confirm this node was the culprit after disabling all of my nodes and slowly reenabling them and testing my ComfyUI. 

I'm not complaining, love the node, but wanted to share this info. I'd rather rollback my ComfyUI update (running on the cloud via Paperspace) but I don't exactly know how... so for now I'll just disable the node.

**Comment by yoland68** [comment]
FYI, you can rollback in the setting in your Comfy frontend.

Also I was able to reproduce this issue and the trace came out to be related to Comfy Easy Use's extension javascript

Can you also check if the you have Comfy Easy Use installed.
![image](https://github.com/user-attachments/assets/fd4c47c5-c82b-448e-9e99-55dd5eb0541f)

**Comment by chrisgoringe** [comment]
Have you got the latest version of UE?

**Comment by jeffufu** [comment]
> Have you got the latest version of UE? This looks very like an issue that was fairly recently fixed...
> 
> I'll look into it when I have a moment!

I believe so! I just did a git pull and it says it's the latest. No rush at all, and it might be something I'm doing wrong too. Thanks!

**Comment by chrisgoringe** [comment]
OK - I've got the latest version up now and can't reproduce the problem. So may be a conflict with another custom node (maybe to one @yoland68 mentioned)

**Comment by jeffufu** [comment]
> OK - I've got the latest version up now and can't reproduce the problem. So may be a conflict with another custom node (maybe to one @yoland68 mentioned)

Thank you for taking a look and sorry for taking up your time! As he noted, it was indeed a conflict with that other node; Use Everywhere works normally after I disabled it. All good now, I think!
