### ISSUE TITLE
Incorrect labelling in everywhere3 node (old code not being cleared)

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [chrisgoringe/cg-use-everywhere#27]
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/52193044/f5ae6310-82c7-48b9-be34-49d6d772fed0)

**Comment by chrisgoringe** [comment]
Yeah, that's not right!

Please update to the latest version, and then if this still occurs, press f12 to look at the javascript console and see if there are any errors that look like they might be relevant.

Sometimes it's easiest to clear the canvas, close the browser, reopen and open a Comfy window (with no workflow), then press f12 to see if there were any error as ComfyUI started up. If not, load your workflow, and look again.

**Comment by GalaxyTimeMachine** [comment]
I updated the custom nodes and ComfyUI, cleared the workflow, closed the browser, restarted ComfyUI and pressed F12...
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/52193044/13f49fc9-5358-46dd-9c1e-9b7250de19c2)
I then just tried adding these 2 nodes and connecting them, this is how it looks as I connect each...
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/52193044/82f8b0b3-f9fa-487b-bd31-c839c5f78cd3)
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/52193044/f5107725-d67d-494b-b405-4e29818e0190)
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/52193044/cf96e425-4cca-47b4-ae71-2324f3ac3447)
The last one I connect is always the name at the top, and it looks like a bug in the node's method of naming.
I tested connecting the bottom ones first, and the name always changes only the top one...
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/52193044/aabbac2e-25a1-4e5a-ae7c-682862e26e2b)
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/52193044/4f9ce8e1-ea70-4f20-82f9-225a45c5eb6e)

**Comment by chrisgoringe** [comment]
Thanks for the very detailed report!

It looks very much like some old code hanging around - I'll need to fix that. You can probably get it working by the method [here](https://github.com/chrisgoringe/cg-use-everywhere#loggingdebugging) - look at the end of that section for  "The other thing worth trying is clearing out all the custom node javascript..." and follow the four steps. Hopefully that will fix it!

**Comment by GalaxyTimeMachine** [comment]
Thanks, but I'd already deleted the everywhere custom nodes folder and re-installed it, and that resolves the issue.
A great set of nodes, thank you! :)

**Comment by chrisgoringe** [comment]
great! Glad that fixed it, I've added some code to the init which should clean up automatically.
