### ISSUE TITLE
Are there any conditions for using the "Anything Everywhere" node?

### ISSUE THREAD

**Issue by nefudev** [chrisgoringe/cg-use-everywhere#28]
I use the UE node conveniently!
I would like to use the new "Anything Everywhere" but I get an error and cannot connect. both UE and comfyUI are up to date. Are there any requirements to use it?

Existing UE nodes are working fine.

![img_0001 5](https://github.com/chrisgoringe/cg-use-everywhere/assets/132149510/bc1c886a-793d-4a2d-a6c6-1119e4128fc3)

**Comment by chrisgoringe** [comment]
Your Everything3 node there isn't working properly for some reason. It should be - but when you connect it up the names should change, so something is broken!

Please update to the latest version, and then if this still occurs, press f12 to look at the javascript console and see if there are any errors that look like they might be relevant.

Sometimes it's easiest to clear the canvas, close the browser, reopen and open a Comfy window (with no workflow), then press f12 to see if there were any error as ComfyUI started up. If not, load your workflow, and look again.

**Comment by chrisgoringe** [comment]
Try updating and see if that fixes it - I've fixed a very similar bug for someone else.

**Comment by chrisgoringe** [comment]
Done in 4.0
