### ISSUE TITLE
Regex don't recognize renamed inputs

### ISSUE THREAD

**Issue by Erehr** [chrisgoringe/cg-use-everywhere#34]
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/13292573/0cefe949-36c1-423b-8918-ca4165746816)

Only default input name is valid, after renaming it input regex still detects it as the original one. In example above If I changed regex to 'images' it would work, even when input name is renamed differently.

**Comment by chrisgoringe** [comment]
Good catch. I'll look into this.
