### ISSUE TITLE
Perfomrance issue when displaying hidden links

### ISSUE THREAD

**Issue by mysteriousHerb** [chrisgoringe/cg-use-everywhere#42]
I think the animation is too much, at least my 3080 cannot handle it somehow :/

**Comment by chrisgoringe** [comment]
Solve as part of #16

**Comment by chrisgoringe** [comment]
Option to turn off animation added to main settings.

**Comment by chrisgoringe** [comment]
Are you sure you have the latest version? And restarted? There should be another menu item under the two you can see.
