### ISSUE TITLE
Almost perfect, any idea how we can work with switches / fastmuter?

### ISSUE THREAD

**Issue by mysteriousHerb** [chrisgoringe/cg-use-everywhere#43]
I have turned most of things wireless, but i am using a few switches and muters that connect across groups.
WOuld you have some nice ideas? 
https://github.com/rgthree/rgthree-comfy#fast-muter

**Comment by chrisgoringe** [comment]
What exactly is it that you'd like it to do? 

Maybe post a workflow and say what you think UE maybe could do but can't?

**Comment by chrisgoringe** [comment]
Unlikely to make this work with something that dynamically changes its own inputs, or use connections in non-standard ways. If there is a specific case you think might be worth covering, open an issue with specific details.
