### ISSUE TITLE
Broken 'any switch' in 'rgthree'

### ISSUE THREAD

**Issue by mijuku233** [chrisgoringe/cg-use-everywhere#45]
### This node makes `any switch` in `rgthree` unusable

![1](https://github.com/chrisgoringe/cg-use-everywhere/assets/89350747/c8736541-a791-4b21-ab4f-b3a9bcdc6130)

**Comment by chrisgoringe** [comment]
Thanks for catching this, and for the great bug report!
Fixed in 4.1.3 
![GIF 14-10-2023 11-19-49 PM](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/160d8389-f171-4b08-9aaa-7cd6babf59a7)

**Comment by pixelpainter** [comment]
having a similar issue, just updated comfyui and nodes, and now I am not able to pass images or text through any switch. These switches were working just fine yesterday, are now no longer working.

Failed to validate prompt for output 38:
* (prompt):
  - Return type mismatch between linked nodes: text, received_type(*) mismatch input_type(STRING)
* ShowText|pysssss 38:
  - Return type mismatch between linked nodes: text, received_type(*) mismatch input_type(STRING)
Output will be ignored
Failed to validate prompt for output 61:
* CLIPTextEncode 23:
  - Return type mismatch between linked nodes: text, received_type(*) mismatch input_type(STRING)
* InstructPixToPixConditioning 35:
  - Return type mismatch between linked nodes: pixels, received_type(*) mismatch input_type(IMAGE)
Output will be ignored
Failed to validate prompt for output 9:
Output will be ignored
Failed to validate prompt for output 40:
* (prompt):
  - Return type mismatch between linked nodes: images, received_type(*) mismatch input_type(IMAGE)
* PreviewImage 40:
  - Return type mismatch between linked nodes: images, received_type(*) mismatch input_type(IMAGE)
Output will be ignored
