### ISSUE TITLE
UE link visibility graphics

### ISSUE THREAD

**Issue by noembryo** [chrisgoringe/cg-use-everywhere#46]
I'm using Anything Everywhere for a couple of days, and I must say its a great workflow improvement.
Thank you for your work.

One thing that is bothering me a little though, is that the UE link visibility dots are flowing using the "Spline" mode cable paths (which BTW look really nice if you use Spline) and create a mess if you use the "Linear" mode..
I know its minor and I could just turn it off, but I think its a pity.. 😉

**Comment by noembryo** [comment]
> Just to clarify - you'd like the UE links (when shown) to use the same path mode as the regular links?

Perhaps I was not clear enough.
What I meant was, that the path that the dot animation is following is not the line of the cables (as is the case with the "Spline" mode cables).
![CableAnim1](https://github.com/chrisgoringe/cg-use-everywhere/assets/24675403/849baf09-4416-4216-a55a-6e7353795ffc)
They follow the curved path not the straight one.
Also the middle dot (that all the cables have) is also offset to the same path.

**Comment by chrisgoringe** [comment]
well that is odd :). Thanks for the report, I'll see what I can work out!

**Comment by chrisgoringe** [comment]
Unfortunately the animation code is part of litegraph core - I've raised an issue there. But not going to rewrite that code for this!

https://github.com/jagenjo/litegraph.js/issues/427
