### ISSUE TITLE
`recursive_follow` have very poor performance during loop check when integrated with other extensions.

### ISSUE THREAD

**Issue by Trung0246** [chrisgoringe/cg-use-everywhere#47]
As said, the function still run correctly but for some reason it appears to be very slow when https://github.com/Trung0246/ComfyUI-0246 have 14 different `Highway` node connected together. I waited for between 30 seconds when saving workflow or running the prompt queue.

**Comment by chrisgoringe** [comment]
I've just added the Highway nodes, hope to work with their author on this.

**Comment by chrisgoringe** [comment]
Just submitted an update - could you check if it makes a difference?

**Comment by Trung0246** [comment]
Looks like it no longer hang for my workflow 👌. Also just tested intentional loop. Looks good so far.
