### ISSUE TITLE
Two Clip Text Encode and String_ nodes from your test workflow.

### ISSUE THREAD

**Issue by Zdeto** [chrisgoringe/cg-use-everywhere#48]
Hi and thanks for this wonderful nodes! :)

I've been trying to reproduce some of your workflows and using the test images got me this error in ComfyUI.
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/34720764/b9ec1f58-8a2e-43be-9373-18a93d9e58d6)

In Manager I can't install the missing nodes, can't find them. I googled and searched and couldn't found what is the "Two Clip Text Encode" node. Please advise, thank you! :)

**Comment by chrisgoringe** [comment]
Apologies - the example workflow has been updated to not use these nodes any more.

Alternatively you can get them here: https://github.com/chrisgoringe/cg-utilities
