### ISSUE TITLE
Doesn't work with reroute nodes?

### ISSUE THREAD

**Issue by CHollman82** [chrisgoringe/cg-use-everywhere#50]
Or am I missing something? I tried using regex match with a custom title on a reroute node and it didn't work.

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/3136566/e9cea7c2-3f2d-4f8e-84d2-4d829d9d0d3e)

Renaming the input slot of the reroute node and targeting that does not work either:

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/3136566/a9c063e9-c6a3-41a8-b4ae-1526a6cac3fb)

**Comment by chrisgoringe** [comment]
From the readme: 

 Connect anything to it (directly - not via a reroute)

Doesn't work with reroute.

**Comment by chrisgoringe** [comment]
Why not just directly target the node you are sending it to?

**Comment by CHollman82** [comment]
Because I'm OCD and wanted it to look a specific way... lol.

No problem, if it's a known issue and impossible or not worth the time to fix you're right it's easy enough to work around. It was mostly for adapting an old workflow more easily, but for anything new it won't even be an issue.
