### ISSUE TITLE
Targeting inputs (that were widgets)

### ISSUE THREAD

**Issue by DrJKL** [chrisgoringe/cg-use-everywhere#52]
I might be missing something, but say that I want to have a Primitive node of type Combo to pick the Sampler (and another for Scheduler). How would I connect this to the UE network to populate the inputs on KSampler nodes?

Connecting a primitive first to type it and then trying to route it to an `Anything Everywhere` or `Anything Everywhere?` node didn't work.

**Comment by chrisgoringe** [comment]
hmmm. Primitives are a pain, but that's a good use case. 

tl;dr - can't be done at the moment, but I'll look into it.

**Comment by DarkAlchy** [comment]
I can't get primitives to work (refuse to connect) and conditioning out of the clip_encoders doesn't work either.  They will connect but the ksampler throws up an error about the lack of connections.

**Comment by chrisgoringe** [comment]
@DarkAlchy , could you post an example workflow - ideally as a new Issue?

**Comment by DarkAlchy** [comment]
> @DarkAlchy , could you post an example workflow (of the conditioning problem) - ideally as a new Issue?

Works now but this goes back to my other ticket now due to having four conditionings).
