### ISSUE TITLE
[FR] Color based matching

### ISSUE THREAD

**Issue by DrJKL** [chrisgoringe/cg-use-everywhere#53]
I haven't checked to see if node color is exposed, but if so could we use it as a cheaper / more visible means of associating the AE nodes with targets? This would be an alternative to setting titles and using the `AE?` with a regex or putting them into groups together.

Example (Not working):
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/448862/3d19f6fd-7b37-47f8-8e1b-21c2dd395e5e)

**Comment by chrisgoringe** [comment]
I love this idea :)

**Comment by chrisgoringe** [comment]
Added in 4.3.1.

Thanks again for a great feature request!
