### ISSUE TITLE
Are we going to get channels?

### ISSUE THREAD

**Issue by DarkAlchy** [chrisgoringe/cg-use-everywhere#54]
What I am asking is the way most programs do it with a transmitter and receiver  so I can have XX amount of a VAE points or latent_image points, etc...  Right now this is not possible.  I still use refiner and it needs its own set of transmitters for the receivers (connection points) it has.  This is why there are receivers and transmitters in other programs that do something like this, so we can have more than just one and done.

**Comment by chrisgoringe** [comment]
Not exactly sure what you are describing, but you can control what goes where using :

(i) the Use Everywhere? nodes (send only to matching title or input regex)
(ii) the group restriction (send only within my group)
(iii) the colour restriction (send only to nodes with the same colour)

Maybe you could post an example of a workflow that this isn't enough for?

**Comment by DarkAlchy** [comment]
How do I send to a matching title?

**Comment by chrisgoringe** [comment]
the two regex's limit where data can be sent. The first matches node title, the second matches input name.

The auto expand is https://github.com/chrisgoringe/cg-use-everywhere/issues/33 and probably won't happen

**Comment by chrisgoringe** [comment]
if you post a workflow I can probably answer your question much more easily

**Comment by DarkAlchy** [comment]
> the two regex's limit where data can be sent. The first matches node title, the second matches input name.
> 
> The auto expand is #33 and probably won't happen

Why not?

**Comment by chrisgoringe** [comment]
because this is a spare time hobby and I pick the things I find most useful or interesting!
