### ISSUE TITLE
Little suggestion : make it glow?

### ISSUE THREAD

**Issue by LuluViBritannia** [chrisgoringe/cg-use-everywhere#59]
Hey there!
Thank you for this amazing custom node. It's a must for everyone!
I only have _one_ issue, a very small one: is there a way to make connected dots glow? Just a little static visual effect that shows that the dots are connected wirelessly.
I know there is the option to make the cables appear, but that's not what I'm asking for. Just a simple visual effect, making the dots glow like Christmas decorations if it is connected, so we know instantly if we forgot to plug an input.

That would be the cherry on top of the cake!

**Comment by chrisgoringe** [comment]
cool idea... let me look into it :)

**Comment by chrisgoringe** [comment]
Done in 4.3.4. Not exactly 'glowing' but a simple visual indication.

**Comment by chrisgoringe** [comment]
Wow. This makes such a difference! Thanks for the suggestion @LuluViBritannia

**Comment by LuluViBritannia** [comment]
Awesome! Now we clearly see what's plugged instantly!
(I still wish we could have them glow though, lol. I'll see if I can add the effect myself.)

**Comment by LuluViBritannia** [comment]
![UEChristmas](https://github.com/chrisgoringe/cg-use-everywhere/assets/14148607/430202f9-aa9d-45de-8eba-740fc21186a5)
I made a little glowing effect ^^. I added a shadow, centered it on the input, then drew a white circle with low opacity on the dot (suggestion by ChatGPT because I had no idea how to do it myself ^^').

![UELinkshighlight](https://github.com/chrisgoringe/cg-use-everywhere/assets/14148607/5321f31a-200e-43ce-8b28-84832582e8da)
Centering the shadow also affected the Link effect. so I figured I'd also change the shadow color to the line's color. I don't use that function at all, but when I tried it, it fitted very well with my glowing effect. It's early Christmas with these effects!

What could I change/add to make it better? I feel like something is missing...

**Comment by chrisgoringe** [comment]
Very nice! Do a pull request 😀

**Comment by LuluViBritannia** [comment]
![Capzerfrtdfbture](https://github.com/chrisgoringe/cg-use-everywhere/assets/14148607/cad5173f-0728-461f-8165-85660c376de8)

Since I had asked ChatGPT to help me with this code, I decided to have fun and do the same with a local LLM. Gave it the exact same code and asked the same thing. Somehow it gave a freaking **better** solution than ChatGPT, lmao!

This is the function with that second glowing effect:

```
    highlight_ue_connections(node, ctx) {
        this.ue_list.all_connected_inputs(node).forEach((ue_connection) => {
            if (!ue_connection.control_node) { // control node deleted...
                this.mark_link_list_outdated();
                return; 
            }
            var pos2 = node.getConnectionPos(true, ue_connection.input_index, this.slot_pos1);
            pos2[0] -= node.pos[0];
            pos2[1] -= node.pos[1];
			ctx.globalAlpha = 1;
            ctx.shadowColor = LGraphCanvas.link_type_colors[ue_connection.type];//LVB modified this and the following paragraph.
			ctx.shadowOffsetX = 0;
			ctx.shadowOffsetY = 0;
            ctx.shadowBlur = 25;
			ctx.stroke;
			ctx.globalAlpha = this.editor_alpha;
            ctx.save();
            ctx.lineWidth = 1;
            var radius=6
            ctx.strokeStyle = LGraphCanvas.link_type_colors[ue_connection.type];
            ctx.beginPath();
            //ctx.roundRect(pos2[0]-radius,pos2[1]-radius,2*radius,2*radius,radius);
            radius = radius - 1;
            ctx.roundRect(pos2[0]-radius,pos2[1]-radius,2*radius,2*radius,radius);
            ctx.stroke();
            ctx.beginPath();
            ctx.strokeStyle = "black";
            radius = radius - 1;
            ctx.roundRect(pos2[0]-radius,pos2[1]-radius,2*radius,2*radius,radius);
            ctx.stroke();
			
			// Add a glow effect to the connection
			let glowWidth = 3;
			ctx.save();
			ctx.globalAlpha = 0.5; // You can adjust this value for desired glow intensity
			ctx.strokeStyle = 'white';
			ctx.lineWidth = glowWidth;
			ctx.roundRect(pos2[0]-radius,pos2[1]-radius,2*radius,2*radius,radius);
			ctx.stroke();
			ctx.restore();
			ctx.lineWidth = 1;
			
            ctx.restore();
        });
    }
```
