### ISSUE TITLE
Issue with using Anything Everywhere? with Int/Float output/input

### ISSUE THREAD

**Issue by pto2k** [chrisgoringe/cg-use-everywhere#61]
I encountered some challenges while attempting to connect certain input/output types using the Anything Everywhere? node. It appears that the node may display multiple output types, even when the actual output is a single type. For instance, the floatToInt node, which should only output an INT value, displays four different types when connected to Anything Everywhere?. This mismatch in data types likely prevents successful connections to nodes that require a strict INT input.

![anywhere](https://github.com/chrisgoringe/cg-use-everywhere/assets/4364117/53a6719a-732b-49e3-9bbf-a993cf4f9a61)

To circumvent this issue for my workflow, I implemented a workaround that involves converting the output to a string format before connecting it to Anything Everywhere?. On the receiving end, an additional conversion node is employed to transform the received string back into a numerical value. This approach ensures compatibility with nodes that demand a specific data type.

**Comment by chrisgoringe** [comment]
I can't reproduce the problem:
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/102994d1-443c-4caa-a9c7-424e8a4b4e7e)
Can you check everything is up-to-date, and also look in the javascript console (press f12) to see if there are any errors. 

The only other possibility is that a third custom node is doing something strange - could you post a list of other custom nodes you are using?

**Comment by pto2k** [comment]
Thank you for looking into it.

These warnings pop up in console when I drag out an Int output. Do they indicate anything?
![Int_1](https://github.com/chrisgoringe/cg-use-everywhere/assets/4364117/7403c934-0e0e-49eb-ba09-a6c284c1be08)

I'm trying to disable some custom nodes for testing.
Is there some output-affecting-code-string I could search in the code?
![CN_List](https://github.com/chrisgoringe/cg-use-everywhere/assets/4364117/225ecd8d-dc77-4f1e-8b71-c8ea4a3511cb)

**Comment by pto2k** [comment]
I've given updating to the latest version a shot and disabled almost all custom nodes, but unfortunately, I'm still unable to get it fixed. 
I would be extremely grateful if anyone could provide suggestions on what I should check or try next. 
Thanks a million in advance!

**Comment by chrisgoringe** [comment]
OK. ComfyUI_ezXY is a bit of a mess (although I have to love it when people put comments in their code like "I wrote this code, but I can't seem to remember how to read it." (https://github.com/GMapeSplat/ComfyUI_ezXY/blob/master/js/ezExtension.js line 216)!

It changes the output types of nodes in ways that are incompatible with UE. 

In their config.yaml you can set `force_numbertype_compatability` to `false` which will probably make that behaviour go away if you want other features. 

Not going to try to make UE compatible.
