### ISSUE TITLE
cg-use-everywhere is overwriting the rgthree-comfy Seed widget

### ISSUE THREAD

**Issue by rgthree** [chrisgoringe/cg-use-everywhere#66]
Looks like cg-use-everywhere is overwriting the Seed value node for [rgthree-comfy](https://github.com/rgthree/rgthree-comfy) and disallowing it to control the seed.

This was reported here: https://github.com/rgthree/rgthree-comfy/issues/62 and saw it on reddit here https://www.reddit.com/r/comfyui/comments/188mj89/ksampler_keeps_changing_random_seed_from_1_to_a/ (not sure if OP is using rgthree there or not).

To reproduce, install both rgthree-comfy and cg-use-everywhere. A clear workflow with the rgthree Seed node, set to -1 / Randomize, and a regular KSampler node. When the KSampler node is even touched, the rgthree Seed changes to a new seed value.

**Comment by rgthree** [comment]
I see... cg-use-everywhere uses graphToPrompt to analyze, which serializes all node values. And rgthree seed node create a new random seed when it's serialized, then puts it back to -1 when the queue is finished.

Problem is, cg-use-everywhere's analyzing isn't queue, so the seed value doesn't reset.

I should see if there's another way to do this rather than relying on the widget serializeValue method.

**Comment by chrisgoringe** [comment]
I can easily add a property to (say) app which indicates that graphToPrompt has been called when not serializing; you could then test for it. So maybe: `app.UeGraphAnalysis = true` before I call graphToPrompt, then false after (except when actually submitting a prompt, of course)

**Comment by rgthree** [comment]
Oh cool. I just fixed it in rgthree-comfy ([981a5eb](https://github.com/rgthree/rgthree-comfy/commit/981a5eb27524b90cdeabeb7a3974f53ebef2aea6)) by ensuring a queue is currently being processed before swapping widget values. That's probably a little safer since other custom nodes could also serialize the graph at any given time, I suppose. Thanks for looking into it.
