### ISSUE TITLE
Some inputs losing connection when reloading (pictures, workflow provided)

### ISSUE THREAD

**Issue by aegis72** [chrisgoringe/cg-use-everywhere#67]
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/56cce5ad-75c4-462e-8b8d-23be7c61b11e)
As an example, sometimes images lose their connection when loaded. If you just reconnect the node...

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/dbcfd0b7-d464-4320-8502-9454a1ed14fd)
It works again. Looks like it is losing its type or something?

Workflow:
[AegisFlow_Anywhere_conversion.json](https://github.com/chrisgoringe/cg-use-everywhere/files/13539956/AegisFlow_Anywhere_conversion.json)

Tiny utility node I hacked together out of WASquatch's Image Batch node to get an image node that could accept a UE link and pass it along to multiple nodes that need the same image input (the controlnet preprocessors, f/e). Hopefully, he'll add such a node and it can be replaced with something from WAS Suite, but for now I use this node a lot. 
[aegisflow-image-pass.zip](https://github.com/chrisgoringe/cg-use-everywhere/files/13539970/aegisflow-image-pass.zip)

**Comment by aegis72** [comment]
I haven't been able to get it to happen since that night. but I do have a different (but similar) issue. Here's a couple minute video showing what is happening, as well as a node and two example workflows (the node is an extended version of CR's "image 4 switch" and is used to send a specific preprocessed image off to a controlnet stack, but here I've cut out all possible extra stuff to make the problem simpler to debug. 

The workflow takes a loaded image, then passes it with UE to a bank of controlnet preprocessors. The image that is specified by the switch is then passed to the inputs of a 3-controlnet stack. 

I had this working in a different workflow, but I realized that my goal of modularity wouldn't be achieved until I could make the template more simple to use/ scalable to N-instances. So I reworked the way I was doing it so that we feed in the target controlnet name once from a string node, and then the image output options are linked to the controlnet preprocessing chooser using UE. The user still has to make some title changes, but not many.

As in the longer video, when I have one, all works well:
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/0addb0f9-8741-4a20-8405-b249a60063e5)

But if I add another stack, most of the connections are lost. All the target names are unique (as far as I see) and so I am unsure why it would be breaking/not linking up to the correct nodes. In the supplemental video, changing the title_regex target to a widget value versus usingthe common input didn't change anything.

Test workflow and "my" node
[2 workflows and nodes.zip](https://github.com/chrisgoringe/cg-use-everywhere/files/13592406/2.workflows.and.nodes.zip)


https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/bc703f71-0256-4b47-a115-9e7d5579ae03


https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/aca79b55-b25f-4fc8-9863-ebf8e49c44aa

**Comment by aegis72** [comment]
One more thing; if I delete a UE sender, and recreate it with a wildly different name, it rewires after I refresh the page. Here, "aaaa" is wiring up after the refresh, but "bbbb" isn't.
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/5719c3ad-9017-4539-b6a3-0f3fcb134340)

Then, after a refresh:
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/9483a84c-42d8-4981-a449-fc1578b517e5)

Note that the refresh doesn't fix anything that is using the string input (although as seen in the supplemental video, the correct name does seem to get passed to the node)

**Comment by aegis72** [comment]
Signs point to the latter; here I changed the string for the title_regex input to "bigglesbam_ipmix" so I think that it isn't using that value as the title_regex after all, since the nodes are still UE-wired (and wouldn't be if this worked how I want it to)

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/09911bb2-2bf7-4e7e-9ce2-eb3437025264)

Is this simply not possible to achieve? I really hope it's a bug and not a limitation of the framework itself or whatever.

**Comment by chrisgoringe** [comment]
Looks like the problem might be with converting the regex to an input. I'll look into that.

**Comment by aegis72** [comment]
Thank you!

**Comment by aegis72** [comment]
Do you have a "buy a coffee" or similar?

**Comment by chrisgoringe** [comment]
OK - take a look at the latest update. There is *limited* support for converting the regex fields to inputs, but I think it should work with your case.

The limitation is that the input to the regex must come directly from a string source (basically a node which just produces a string literal). I've added a `Simple String` node that works with it.

Yes - https://www.buymeacoffee.com/chrisgoringe

**Comment by aegis72** [comment]
Thanks! Will try in a sec....coffee sent!

**Comment by aegis72** [comment]
https://github.com/chrisgoringe/cg-use-everywhere/assets/118572301/32676d26-de48-456c-9b53-a3162c428d50

Here's loading some stuff via templates and having it wire up.

**Comment by chrisgoringe** [comment]
Hey @aegis72 , I just wondered if you were aware of the feature where you can limit where a UE node sends to the group(s) it is part of. That might be another way to do the sort of thing you needed this for.

**Comment by aegis72** [comment]
Yes; in this case it wouldn't have solved it for reasons too long to
explain since in waiting at a light ;)

**Comment by aegis72** [comment]
Now that I have more time, it would have fixed it if I didn’t care about
modular reuse as much.

Imagine if I had a workflow with 4 samplers, and I wanted 3 to use the same
control net and one to use a different one, but I also wanted to keep the
wireless connection because part of the concept is things wire mostly
automatically and can be moved around without chains of wires. Since I
can’t use variables from UE nodes outside a group if I turned it on, I’d
have to rename many nodes to new names which is worse than wiring, or use
wires and connect everything up every time, which is also undesirable.

Because of your fix, I am able to have one “preprocess nodes” template, and
all they have to do is change that one string field and match the title of
the “preprocess chooser” field, and dozens of things wire themselves, but
the processors are tucked away in a corner without distracting from the
main workflow :)
