### ISSUE TITLE
Document solution to.... UE for list-select widgets converted to inputs.... (Method to apply Anything to various inputs?)

### ISSUE THREAD

**Issue by alenknight** [chrisgoringe/cg-use-everywhere#69]
maybe an enhancement suggestion...as  i couldn't find any prior issue directly addressing this (though i see something similar often repeated )... say i want to set scheduler to be global.
I go to my ksamplers, set scheduler to be "input"
then when i use the everything/anywhere node.... i'd like that to affect all the schedulers that have input

is this possible?  or is it part of that issue where you mentioned recently that reroute nodes are difficult?

**Comment by chrisgoringe** [comment]
Currently not possible. It's not quite like the reroute nodes, but it's not totally separate either. Anything that is a dropdown has a weird data type.

Renaming this to remind me to think about it more....

**Comment by Lex-DRL** [comment]
So, what's the solution? I'd like to have both sampler and scheduler set in one place.
That issue is closed, but I still can't connect a primitive to either `Anything Everywhere` or `Anything Everywhere?`.

**Comment by chrisgoringe** [comment]
This issue is open.

**Comment by Lex-DRL** [comment]
As a quick solution - maybe, for now, just add statically-typed `Sampler everywhere` and `Scheduler Everywhere` nodes?
Most other list-type inputs are related to model selection, and when they're used, you better off passing the loaded model itself anyway. Which is statically-typed, too.

**Comment by DrJKL** [comment]
[UE_sampler_control_example.json](https://github.com/chrisgoringe/cg-use-everywhere/files/13619266/UE_sampler_control_example.json)
![UE_sampler_control_example](https://github.com/chrisgoringe/cg-use-everywhere/assets/448862/bf5725dd-0432-439f-a7d7-dd2bbf9a33d2)

I think I found another way to do it for now.

CustomSampler, provide the sampler and sigmas via UE.

**Comment by Lex-DRL** [comment]
It's nice... but it basically makes any other sampling nodes incompatible with UE. Like, effeciency pack, impact pack or similar.

**Comment by DrJKL** [comment]
I wonder if they could change their widget/input to be compatible with the built-in Sampler/Sigma providers

**Comment by Lex-DRL** [comment]
Ooops... my bad. I didn't know there already exists a `KSamplerSelect` node. And I just discovered that I already have a node to choose a scheduler. It's a part of [comfy-image-saver](https://github.com/giriss/comfy-image-saver).

... However, `Anything Everywhere ?` doesn't seem to work with the bundled `KSamplerSelect`:
![Screenshot](https://github.com/chrisgoringe/cg-use-everywhere/assets/3897975/688725d0-35b1-4c63-80a1-a60efc0715bd)

**Comment by Lex-DRL** [comment]
Oddly enough, it **does** work with the node from [image-saver](https://github.com/giriss/comfy-image-saver).

**Comment by DrJKL** [comment]
I think the KSampler expects a `string` but KSamplerSelect provides a `SAMPLER`

**Comment by Lex-DRL** [comment]
Great. I have a solution for now, with no need to create any custom nodes. `Anything Everywhere?` from your repo + `Sampler Selector` / `Scheduler Selector` from the aforementioned image-saver repo.

And since there is already a node for that, I don't think you need to add your own doing the same thing. Though, you might want to add this workflow suggestion to readme.

**Comment by alenknight** [comment]
good move with the sampler/scheduler selectors.  I'll start incorporating them in my workflows

**Comment by alexopus** [comment]
> It's nice... but it basically makes any other sampling nodes incompatible with UE. Like, effeciency pack, impact pack or similar.

+1.
While the solution with KSamplerSelect & BasicScheduler to SamplerCustom works for regular KSampler, it would nice to have a more general one to support any kind of sampler. To name a few: KSampler (inspire), Ultimate SD Upscale, FaceDetailer, Tiled KSampler...

The difference between KSamplerSelect and Sampler Selector from image-saver seems to be the type:
https://github.com/comfyanonymous/ComfyUI/blob/master/comfy_extras/nodes_custom_sampler.py#L164
https://github.com/giriss/comfy-image-saver/blob/main/nodes.py#L150
Where the latter matches the the type from USDU, inspire & co: https://github.com/giriss/comfy-image-saver/blob/main/nodes.py#L150 and KSamplerSelect does not.

**Comment by alexopus** [comment]
For reference, there is now a way to control sampler/scheduler globally in the inspire pack: https://github.com/ltdrdata/ComfyUI-Inspire-Pack/commit/fb7ebc7bdf1b737a2e271041101d40db2de53cfa#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by chrisgoringe** [comment]
Or do with #91

**Comment by PabloMontero** [comment]
> Great. I have a solution for now, with no need to create any custom nodes. `Anything Everywhere?` from your repo + `Sampler Selector` / `Scheduler Selector` from the aforementioned image-saver repo.
> 
> And since there is already a node for that, I don't think you need to add your own doing the same thing. Though, you might want to add this workflow suggestion to readme.

This is working for me too :)

Please keep posting new findings. Good job!

**Comment by chrisgoringe** [comment]
Closing this - but I've referenced it in the docs. Thanks to those who worked out solutions!

Regarding working with third party samplers - I'd be encouraging their authors to make them work with the built in Sampler and Sigma types...

**Comment by JorgeR81** [comment]
You can also use the KSampler Config (rgthree) node, which has COMBO widgets for sampler and scheduler.
And you can even group it with "float" nodes from Impact pack, to add extra KSampler parameters, like denoise. 
This works with the "vanilla" KSampler !

![rg3k](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/bb74f38c-3fb7-4589-a1b2-a4fa77ffbf43)

![rg3](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/11f07b16-da3d-42e8-a31e-8b3172ab5620)

**Comment by JorgeR81** [comment]
And it also works with samplers from other node packs, like FaceDetailer ( Impact Pack )

![dfet](https://github.com/chrisgoringe/cg-use-everywhere/assets/72734038/5f738b7a-598c-42b6-ad11-410048b08d09)

**Comment by JorgeR81** [comment]
In seems there is also a workaround, with the `CR String To Combo` node from ComfyUI_Comfyroll_CustomNodes.
This should work for any cases ( e.g. preprocessor selector  ).
But we need to use the Simple String node for the UE? node input, so no dropdown list.

https://github.com/Fannovel16/comfyui_controlnet_aux/issues/289#issuecomment-2027461249
