### ISSUE TITLE
UE to Generate "Progress Messages" (Socket.io)

### ISSUE THREAD

**Issue by kenster4000** [chrisgoringe/cg-use-everywhere#70]
UE would be great to help broadcast messages to websockets for a frontend using Comfy API to display progress on front-end. Is there a way to capture/log which node is being processed?

**Comment by chrisgoringe** [comment]
Not sure why UE is especially suitable for the task?

**Comment by kenster4000** [comment]
@chrisgoringe was just thinking that given the work you've put into operating more globally to a workflow, rather than having something directly in the chain trying to trigger progress - UE is already the closest to being able to tap into these events as a global node. I guess it could be a completely new custom node - just saw this as a potentially easy QoL thing.

**Comment by chrisgoringe** [comment]
@kenster4000 my Image Picker node - https://github.com/chrisgoringe/cg-image-picker - has a HUD which shows the currently active node, is that the sort of thing you are talking about? It would be easy to pull that code into a standalone node and add sockets to it.

But if you are talking about doing this when using the ComfyAPI without the web interface, it would be a different problem.

**Comment by kenster4000** [comment]
@chrisgoringe ah nice. however - yeah the goal is for use during ComfyAPI - allowing the workflow to communicate back via sockets to the frontend regarding process. (e.g. Now Splitting Frames..., Now Generating..., Now Face Swapping, etc.). Any possible solutions jump to mind based on your Image Picker code?

**Comment by chrisgoringe** [comment]
No - the Image Picker code doesn't really touch the python backend, which is where this would need to be done.

**Comment by chrisgoringe** [comment]
I'd suggest this is actually a suggestion for the core Comfy code. I don't think it would be hard to do, but I don't think it can be done by a custom node.
