### ISSUE TITLE
Loop (191,8,64,87,133,57) with broadcast (139) - not submitting workflow

### ISSUE THREAD

**Issue by chrisprojs** [chrisgoringe/cg-use-everywhere#71]
![Screenshot 2023-12-06 232905](https://github.com/chrisgoringe/cg-use-everywhere/assets/111422870/fa4274da-2a1c-49ce-aadf-6210bc48263c)
I got this error, even i close window, restart, git pull the repository. It still not work

**Comment by hebwugyenatps** [comment]
你可能有节点经过连接又串回到了这个节点上，我刚好遇到了这个问题，属于循环判定，我将controlnet的输出条件连接到flux引导，flux引导的输出又连到了controlnet的输入条件上，就报错了，你看一下是不是也有这个问题

**Comment by hebwugyenatps** [comment]
You may have a node that has been connected and then strung back to this node. I happened to encounter this problem, which belongs to loop judgment. I connected the output condition of Controlnet to Flux Boot, and the output of Flux Boot was connected to the input condition of Controlnet, but it reported an error. You can see that it is not the same problem
