### ISSUE TITLE
Suggestion: A manager button or interface right-click menu item that highlights name conflicts

### ISSUE THREAD

**Issue by aegis72** [chrisgoringe/cg-use-everywhere#73]
Most problems seem to happen when sending names conflict (IE, two send nodes that have the same target name) ; it would be cool to see any occurrences of naming conflicts in the graph that UE is getting so that debugging these issues could be easier. 

One other thought, and this may not be possible w/in comfy, would be to add a "group regex". IE, only send commands to the nodes inside a group with  title "whatever".

**Comment by chrisgoringe** [comment]
Pulling the second half of this out as a separate issue #74

**Comment by chrisgoringe** [comment]
For the first half: I've updated the logging to make it much more informative. If there is a clash, the javascript log now includes something like:

```
'DisplayText' (4) input 'text' matches multiple Use Everwhere sources:
  - Anything Everywhere (6) input 0
  - Anything Everywhere (8) input 0
```

Do you think it would be valuable to be able to show this in the GUI as well?

**Comment by aegis72** [comment]
Astonishingly helpful!

**Comment by chrisgoringe** [comment]
Added in 4.5.1 - right-click on background and select `Show UE broadcast clashes` (only appears in menu if there is a clash).

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/4371971/eb495705-2694-4ae4-9790-978005347564)

**Comment by aegis72** [comment]
Amazing!
