### ISSUE TITLE
Error connecting rgthree Seed to Seed Anywhere

### ISSUE THREAD

**Issue by ParthGandhi** [chrisgoringe/cg-use-everywhere#75]
![Screenshot 2023-12-13 at 11 24 04 AM](https://github.com/chrisgoringe/cg-use-everywhere/assets/819237/f45fd05b-89ee-40ab-ba11-48315cba4402)

**Comment by chrisgoringe** [comment]
Seed anywhere is not designed to be used with an input.

If you need to do this, use 'Anything Everywhere?' node with an input regex of "seed".
