### ISSUE TITLE
Negative Regex Possible?

### ISSUE THREAD

**Issue by Gerkinfeltser** [chrisgoringe/cg-use-everywhere#77]
Hi, just curious as my regex isn't the strongest but is there a way to use the Anywhere? nodes match all **but** a string combo? I've tried a few ways but haven't been able to get them to work. Maybe this isn't possible though.

Even if not thanks so much for the great extension though! No more noodle soup!

**Comment by chrisgoringe** [comment]
It's using javascript `regex.test()` to find a match, so it is a positive match that's being looked for. But it is possible to do some things by enforcing the start and/or end (with `^` and/or `$`) and then using the negation sets (`[^x]` means anything but x) to do things like:

-  `^[^x]*$`  - match anything which doesn't contain an `x`
- `^[^s]` - match anything that doesn't start with an `s`
- `[^0-9]$` - match anything that doesn't end in a digit

I'm not really a regex guru, but https://regex101.com/ is really helpful for working out regexes.

**Comment by chrisgoringe** [comment]
I've added https://github.com/chrisgoringe/cg-use-everywhere/issues/78 to consider, closing this.

**Comment by Gerkinfeltser** [comment]
Thank you for the thorough reply. I definitely wasn't doing the right regex then. Will give your examples a try today. Thanks again!
