### ISSUE TITLE
Switch to turn off missing filter spam

### ISSUE THREAD

**Issue by Amorano** [chrisgoringe/cg-use-everywhere#80]
A simple switch, or elevated log level to remove the excessive spam for things that are obviously not looking to be filtered would be welcome.

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/225178/d5288f92-3793-4686-8b8d-213c07f6b370)

**Comment by chrisgoringe** [comment]
moved this message to INFORMATION log level in 4.4.4
