### ISSUE TITLE
Translate Prompt and Seed built in regex's (was: In the Chinese interface, the 'Prompts Everywhere' node is not functioning at all. Can this be fixed?)

### ISSUE THREAD

**Issue by wibur0620** [chrisgoringe/cg-use-everywhere#81]
I am using this Chinese localization plugin: https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION. 

https://github.com/chrisgoringe/cg-use-everywhere/assets/131615326/c90925d4-c38c-4b03-b0af-da2db43bd7b8

**Comment by wibur0620** [comment]
![屏幕截图 2023-12-21 005644](https://github.com/chrisgoringe/cg-use-everywhere/assets/131615326/201df87f-ccd6-48b4-9918-79458540dd2a)
The "Seed Everywhere" node did not take effect.

**Comment by chrisgoringe** [comment]
Right. Both those nodes work with regex's which are based on the English character set. I will look at this.

I've open an issue https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues/133 to see how I can work with that node creator to do this properly.

**Comment by chrisgoringe** [comment]
Possibly solved by https://github.com/chrisgoringe/cg-use-everywhere/pull/85 in 4.4.4
