### ISSUE TITLE
Comfy API not working

### ISSUE THREAD

**Issue by vqt123** [chrisgoringe/cg-use-everywhere#82]
I don't believe UE works when exporting out an API workflow for API access

**Comment by DrJKL** [comment]
I think that's dependent on https://github.com/chrisgoringe/cg-use-everywhere/issues/55

**Comment by chrisgoringe** [comment]
Yes, DrJKL is correct. This is a good reason to do #55 !

**Comment by chrisgoringe** [comment]
Should now be able to replace all UE links with real links (right click on backdrop) and then export
