### ISSUE TITLE
Unable to proceed with workflow

### ISSUE THREAD

**Issue by Yinghaiyulin** [chrisgoringe/cg-use-everywhere#86]
After using this plugin, it cannot work at all. It can only be uninstalled. What is the reason for this? Is there a solution?
https://github.com/chrisgoringe/cg-use-everywhere/assets/73933317/cdcfdbeb-912e-4e0b-ac3d-a0ebd3d9c7bf

**Comment by shareach** [comment]
> Please could you look in the Javascript Console for errors? This looks like it is probably an incompatibility with another custom node but impossible to tell with just that video.

the same problem,  https://github.com/chrisgoringe/cg-use-everywhere/issues/98

**Comment by chrisgoringe** [comment]
Please check if comfy ui is up to date.

**Comment by chrisgoringe** [comment]
closing for lack of additional information
