### ISSUE TITLE
UE Links are not working when 'Convert to Group Node'

### ISSUE THREAD

**Issue by MaisonMeta** [chrisgoringe/cg-use-everywhere#88]
Comfy recently added the possibility to convert multiple nodes into one. Ive been doing testing and it seems the the UE links are not working anymore when the new nodes are being created. 

Has anyone experienced this issue as well ? 
Is there a potential fix coming in soon ?

**Comment by chrisgoringe** [comment]
Yes, see #84. I'm travelling at the moment but making this work will be a priority. ETA late January.

**Comment by MaisonMeta** [comment]
Amazing Chris! Thank you so much. will test it now!
