### ISSUE TITLE
Doesn't work with COMBO

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-use-everywhere#91]
- add a KSampler
- convert scheduler to an input
- double-click the input to create a primitive COMBO
- try to drag the COMBO onto a UE node

**Comment by chrisgoringe** [comment]
onConnectionsChange never gets called; must be being rejected as an invalid link earlier in the core code

**Comment by BigBlueGX** [comment]
A solution is this

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/121982987/0739ce30-e0a2-4515-9cbe-7c528c2a4057)

**Comment by PabloMontero** [comment]
> A solution is this
> 
> ![image](https://private-user-images.githubusercontent.com/121982987/295117470-0739ce30-e0a2-4515-9cbe-7c528c2a4057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MzY2OTUsIm5iZiI6MTcwNTgzNjM5NSwicGF0aCI6Ii8xMjE5ODI5ODcvMjk1MTE3NDcwLTA3MzljZTMwLWUwYTItNDUxNS05Y2JlLTdjNTI4YzJhNDA1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQxMTI2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWVjMDhmMzJlMDg1MTY4NmMxMTE3NTU3MjZkNjU2OWRjMzU0OTQzMjM4OWY1NzNjNTMyNmEzZDJmZDAxYmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6ZMAC1kUSU0ZVPXxD1IgutWWbWn3qlwOIMdXc2oUpUI)

Sorry, I cannot find "Collection Primitive" node. Is it built-in?

**Comment by PabloMontero** [comment]
> * try to drag the COMBO onto a UE node

I am completely lost in this last step :_(

**Comment by chrisgoringe** [comment]
See https://github.com/chrisgoringe/cg-use-everywhere/issues/69
