### ISSUE TITLE
effective_node.inputs[down_slot] is undefined

### ISSUE THREAD

**Issue by alexopus** [chrisgoringe/cg-use-everywhere#92]
After updating today, workflow doesn't run anymore.
Console reveals:
```
Uncaught (in promise) TypeError: effective_node.inputs[down_slot] is undefined
    analyse_graph extensions/cg-use-everywhere/use_everywhere.js:62
    analyse_graph extensions/cg-use-everywhere/use_everywhere.js:41
    analyse_graph extensions/cg-use-everywhere/use_everywhere.js:33
    graphToPrompt extensions/cg-use-everywhere/use_everywhere.js:241
```

Maybe related to: https://github.com/chrisgoringe/cg-use-everywhere/commit/2229739074ec7778b5948ea5a306492267d5ec4e? Seems to be, reverting this commit fixes it.

**Comment by drumicube** [comment]
Same situation for me, reverting also fixed the problem.

**Comment by chrisgoringe** [comment]
temporarily reverted main
