### ISSUE TITLE
Cannot connect a Primitive node

### ISSUE THREAD

**Issue by PabloMontero** [chrisgoringe/cg-use-everywhere#93]
Hi,

Amazing job here, I'm in love with Anything.

One issue: I noticed I cannot connect a **Primitive** to _Anything Everywhere?_ Literally I cannot link between them.

Am I doing something wrong?

**Comment by chrisgoringe** [comment]
No, you're not doing anything wrong! There are some technical issues that make primitives tricky. I hope to get them working - no clear timeline, but it is near the top of my list.

**Comment by PabloMontero** [comment]
Cool, please keep this project up. Thank u!

**Comment by chrisgoringe** [comment]
Update... I don't think this is likely to happen, due to the way ComfyUI deals with primitives.

What is the use case for this? Perhaps there is a workaround...
