### ISSUE TITLE
(specify encoding in acript) was: new widget group_regex in AnythingEverywhere? node breaks existing workflows

### ISSUE THREAD

**Issue by karl-von-knecht** [chrisgoringe/cg-use-everywhere#95]
The AnythingEverywhere? node used to have only two widgets, tile_regex and input_regex. It now has a third, group_regex. Unfortunately, when loading a pre-existing workflows, the new widget is not initialized with ".*" 
Instead it seems to be filled with whatever was last sent to the node.
![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/123109169/2f4844d5-82ab-496c-834f-38cc7bf73902)

As a consequence, when I load a workflow with an AnythingEverywhere? node in it, the node will not link to anything until I manually fix all the group_regex widgets (and believe me, I have a lot of those).

**Comment by chrisgoringe** [comment]
Thanks for the report. I'm travelling at the moment but I'll see if I can fix this...

**Comment by aegis72** [comment]
I had to fix them as well in my very complex WF, but it was to me just the price of admission :). The Group RegEx is extrmely powerful and solved a TON of expandability issues, but it did mean I had about 2 weeks of work to integrate them. I'd never go back though.

**Comment by chrisgoringe** [comment]
Could someone post an *unfixed* json file? Since this is a transition issue I might just write a script to fix the json directly

**Comment by aegis72** [comment]
I'll try to find an older version if Karl doesn't come in first. It isn't really a problem for me anymore :)!

**Comment by karl-von-knecht** [comment]
Here is one
[workflow pastel.json](https://github.com/chrisgoringe/cg-use-everywhere/files/13961692/workflow.pastel.json)

**Comment by chrisgoringe** [comment]
I just pushed an update which adds a new script. You can run it on workflows that were saved before the change, and it will just set the third widget of every `Anything Everywhere?` node to `.*`

`python workflow_fixer.py broken_workflow.json new_name.json`

will load `broken_workflow.json` and resave it as `new_name.json`

I'll close this issue now, please feel free to reopen if this doesn't work.

**Comment by karl-von-knecht** [comment]
Hi chris,

huge thanks for this, you made my day!

I did encounter a tiny, little bug:

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/123109169/d9e4ac32-4ab0-410f-9a58-22896b442100)

The offending character is the "snake" character in the title of the pythongossss ShowText:

![image](https://github.com/chrisgoringe/cg-use-everywhere/assets/123109169/e3b0cc0c-ded3-47b8-a312-387f117f1615)

After I removed this character, your script worked fine.

**Comment by chrisgoringe** [comment]
Ah, I ought to specify the encoding when I read the json. Thx.
