### ISSUE TITLE
Connecting Sampler and Scheduler to a KSampler

### ISSUE THREAD

**Issue by PabloMontero** [chrisgoringe/cg-use-everywhere#97]
Hello,

maybe it's not a problem with Anything, but I cannot find a solution for this issue:

I want to use Anything with almost all parameters of a KSampler (Advance). But I really don't find the way to connect the **Sampler** and the **Scheduler**. I've try in several ways, but it seems they don't match well with Anything, I cannot make it works.

Any suggestion? Thank you!

**Comment by chrisgoringe** [comment]
See this thread which might help https://github.com/chrisgoringe/cg-use-everywhere/issues/69

**Comment by PabloMontero** [comment]
Thank you!
