### ISSUE TITLE
the whole comfyui can't work

### ISSUE THREAD

**Issue by shareach** [chrisgoringe/cg-use-everywhere#98]
![20240121095304](https://github.com/chrisgoringe/cg-use-everywhere/assets/2534156/4713f173-c3c2-45e5-9259-c309382aa5f7)
click the "queue prompt" report the js error

**Comment by chrisgoringe** [comment]
Please check your version of comfyui is up to date.

**Comment by chrisgoringe** [comment]
This is caused by an out of date version of Comfy 

https://github.com/comfyanonymous/ComfyUI/pull/1677
